### ISSUE TITLE
[Feature] Search functionality

### ISSUE THREAD

**Issue by Lokydoki** [nptr/msstyleEditor#1]
Hi, I've just discovered your little tool and I gotta say I've searched and some good softwares are lacking.
I begin to mess around with it but could you add to your roadmap a few function to make it usable on a whole msstyle editing scale? 
Right now it I see these functionnalities who might be mandatory : 
- search ( in object names/classs or in value )
- search and replace ( with next occurence button and replace all function)

What do you think about it ?
My coding skills are limited but I'll try to look to your code and find some hints to do that

Will keep you posted
Cheers

**Comment by nptr** [comment]
Yep, had this in mind for a while, so definately worth a shot.

**Comment by nptr** [comment]
Added a search function in V1.2.1.0.
