### ISSUE TITLE
Error saving file: "Updating string resource with id '7' failed with error '50'!"

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [nptr/msstyleEditor#100]
I want to save the MSSTYLES file including MUI with the new option from the dropdown arrow under “Save”. An error shows “Updating string resource with id '7' failed with error '50'!”. The Windows version is 18363.1139.

**Comment by nptr** [comment]
You could attach the folder of the visual style in question (with its subfolder etc.). Maybe I can reproduce the error locally.
I think msstyleEditor is accidentally trying to update a resource that is located in a MUI file rather then the .msstyles file.

**Comment by nptr** [comment]
I found and fixed the issue with version 2.0.0.7.

**Comment by Thespikedballofdoom** [comment]
I'm still having this while trying to save or test this theme on versions of msstyleeditor beyond 2.0.0.6. Can't even save it unmodified, 2.0.0.6 saves fine though.
https://www.deviantart.com/scope10/art/Penumbra-10-Windows-10-visual-style-568740374

![image](https://github.com/nptr/msstyleEditor/assets/43627353/e686f7b0-ca6f-4b04-92c7-ce02a5abd78c)
