### ISSUE TITLE
Modified a them I found (Nord), now systray and other right-click menus look like this.

### ISSUE THREAD

**Issue by Paradoxum** [nptr/msstyleEditor#106]
![Untitled](https://user-images.githubusercontent.com/6451395/210451444-74c83c6d-7681-4b87-bc8e-211bedfb9f32.png)
*Windows Version*: W11 22H2

**Question**
All I changed in the theme was the colour of a single bit of text, saved it, applied, my change worked but most right-click context menus are broken like this allover windows now.

**Things you already tried**
Googling it.

**Additional context**
Pretty simple problem. See image.

**Checklist**
- [x ] My uxtheme.dll is patched
- [x ] I am using the latest version of msstyleEditor
- [x ] I checked the Wiki
- [x ] None of the other issues cover this

**Comment by nptr** [comment]
I assume the context menu buttons background should match the menu border (light gray for the left image and dark gray for the right one)? And the text on the right image should be white?

If you send me the original and the modified .msstyles file, I can do a binary diff and see if something broke. But this looks more like some yet unexplained themeing engine shenanigans to me.
