### ISSUE TITLE
How to Fix This Issue With Explorer?

### ISSUE THREAD

**Issue by Shikamaru30** [nptr/msstyleEditor#107]
*Windows Version*: <<Windows 11 21H2 22000.1335>>

**Question**
How do I get rid of the black bars beneath the dropdown menu location and text, or how do I change the color of the whole area shown in the screenshot?

**Things you already tried**
I went through all changes I made, and none of them should have caused this issue. I even checked to make sure by removing changes, but to no avail...

**Additional context**
Here's the screenshot of what I want to fix:
![image](https://user-images.githubusercontent.com/82041382/211200141-8d41db2f-a623-4008-a66b-482bd12d0e4a.png)

**Checklist**
- [ ] My uxtheme.dll is patched (YES)
- [ ] I am using the latest version of msstyleEditor (YES)
- [ ] I checked the Wiki (YES)
- [ ] None of the other issues cover this (YES)

**Comment by nptr** [comment]
Would you mind sharing how you solved the problem? Maybe its something other people need as well. Maybe its suited for the wiki.
