### ISSUE TITLE
Premultiply and un-premultiply alpha when exporting / replacing image

### ISSUE THREAD

**Issue by Simplestas** [nptr/msstyleEditor#108]
**Is your feature request related to a problem? Please describe.**
PNGs inside msstyles use premultiplied alpha images, but editors expect non-premultiplied alpha

**Describe the solution you'd like**
Automatically un-premultiply alpha when exporting image and automatically premultiply alpha when replacing.

**Describe alternatives you've considered**
Some helper tools can do alpha pre-unpre/mutltiplication

**Comment by nptr** [comment]
Thanks for the info. Not sure what I'll do. Performing this step doesn't seem to be something msstyleEditor should be doing.

But I'll investigate what the common practices are in this regards and if really all styles images must be premultiplied.

**Comment by Simplestas** [comment]
Here's a crude patch for that, too bad that netfx SaveFileDialog does not allow adding checkboxes
[premult.patch](https://github.com/nptr/msstyleEditor/files/10474047/premult.patch)

**Comment by Undisputed00x** [comment]
Any update on this? 
This feature is extremely helpful as it fixes visual issues on pngs especially in glass windows. 

<details>
<summary>

### PNG Unpremultiplied alpha

</summary>
<p>

![Screenshot 2024-11-30 130526](https://github.com/user-attachments/assets/d217c3de-c8cd-4e79-ac7c-37efd82a3394)

</p>
</details>

<details>
<summary>

### PNG Premultiplied alpha

</summary>
<p>

![Screenshot 2024-11-30 130917](https://github.com/user-attachments/assets/84306f17-4065-4682-b6a2-d7ff6def1ec8)

</p>
</details>

**Comment by nptr** [comment]
Sorry, no news. I did sit down just now and investigate and experiment a bit. Here is where i am at:

1.  @Simplestas reported that the colors in the images are actually premultiplied. The images inside the msstyles file are in PNG file format. The PNG file format specifies straight alpha. If the colors were in reality stored premultiplied, that would indeed confuse standard conforming editors and require conversion.

2. The solution attempt from the patch file attached to this issue does not seem to do what it should? See commented code below. 
```csharp
// Image export (MainWindow.cs:626)
MemoryStream ms = new MemoryStream(m_selectedImage.Data);
Bitmap b = new Bitmap(ms); // Load into memory - ok
BitmapData bitmapData = b.LockBits(new Rectangle(0, 0, b.Width, b.Height), System.Drawing.Imaging.ImageLockMode.ReadOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb); // get buffer w/ straight alpha/unchanged
Bitmap b2 = new Bitmap(b.Width, b.Height, bitmapData.Stride, System.Drawing.Imaging.PixelFormat.Format32bppPArgb, bitmapData.Scan0); // Convert to premultiplied? Shouldn't it be vice versa?
b2.Save(sfd.FileName, ImageFormat.Png);
```


3. The images look fine to me in the current state. Shouldn't my image viewer be confused as well if the images were premultiplied against PNG spec? Exporting the images with the patch applied has them look lighter or darker, loseing color information in the process.
![grafik](https://github.com/user-attachments/assets/bd4ee5a0-82d0-431b-8c99-3f3ec9ed7735)



I feel I am missing something here!

**Comment by Undisputed00x** [comment]
When i replace pngs in msstyleEditor i get the "unpremultiplied" version.
Here the png in the example exported from Figma, used on `DarkMode_ItemsView::ListView > ListItem`

![Button](https://github.com/user-attachments/assets/57fbf1bc-87a8-436f-8bee-466f6abd23f2)

Here is the premultipied version of the image exported by [Create-Aero-Compatible-PNGs-V2](https://www.deviantart.com/thoriumknight/art/Create-Aero-Compatible-PNGs-V2-262526394) or [premultiply-alpha](https://github.com/manbeardgames/premultiply-alpha)

![Button_P](https://github.com/user-attachments/assets/e6ba6a5d-6f9c-4a6f-b00b-14c4f49a9ef7)

**Comment by nptr** [comment]
Looks like DWMWindow (and probably all STREAM resources) are not premultiplied.
The rest probably is! I checked the older "Button" class and the newer "Taskband2". Both seem premultiplied and so is probably the stuff "between" them.

How to check:

- If any pixels color channel has a value higher then the corresponding alpha channel, its straight alpha (not premultiplied).
- Otherwise, its ambigous. If there are pixels where r=g=b=alpha there is a good chance its premultiplied however (result from pure white with premutliplied alpha gradient)

**Comment by nptr** [comment]
The [latest pre-release version 2.1.1.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.1.0) now automatically converts the image to/from premultiplied alpha.
- imported images are assumed to be straight alpha (as per PNG specification), and thus converted to premul. alpha.
- exported images are assumed to be premultiplied alpha and thus converted to PNG standard conforming straight alpha.
- STREAM resources (DWMxxxxxx classes) are never converted, because they already come as straight alpha.

Let me know if everything works as expected or if you encounter any bugs. Thank you for your patience!

**Comment by Undisputed00x** [comment]
> The [latest pre-release version 2.1.1.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.1.0) now automatically converts the images to/from premultiplied alpha.
> 
>     * imported images are assumed to be straight alpha (as per PNG specification), and thus converted to premul. alpha.
> 
>     * exported images are assumed to be premultiplied alpha and thus converted to PNG standard conforming straight alpha.
> 
>     * STREAM resources (DWMxxxxxx classes) are never converted, because they already come as straight alpha.
> 
> 
> Let me know if everything works as expected or if you encounter any bugs. Thank you for your patience!

Nice, imported PNGs are fixed. This resolves one of the 2 major issues for me (the other is DPI imagefiles)
Thanks for keeping this software alive.
