### ISSUE TITLE
W11: Edit TaskManager grid control?

### ISSUE THREAD

**Issue by tistoubapt** [nptr/msstyleEditor#109]
*Windows Version*: Win11 22h2

Hello

I don't know if this is the right place to ask this, sorry in advance
And thanks for your great work

I would like to modify the task manager of W11 (grid, outline of the grid) for the CPU, RAM, etc...

Is it possible ?

And is there a help (tuto) to know where is certain class?
For example, changing the color of the inactive title bar, etc...

Thanks for your help

**Comment by nptr** [comment]
It's perfectly fine. The "Discussion" section would also have worked.

Unfortunately I don't know the answer. I also don't have W11 and can't investigate myself. 

I think there was a "TaskManager" (?) class that was used at least in W7 for some some things. But I doubt you'll find what you need there.

Maybe Microsoft just used some system brushes to draw the grid, then there might be a chance to change it (although together with all other things that use the same brush). Worst case, they hardcoded the color with complete disregard of their own system. Then you are out of luck.

**Comment by tistoubapt** [comment]
Ok, thanks for your answer
