### ISSUE TITLE
msstyleEditor disappears when opening a file

### ISSUE THREAD

**Issue by bundyal** [nptr/msstyleEditor#11]
I have the msstyleEditorX64 1.3 and i want to try is on my Windows 10 v1803.
It start up msstyleEditorX64 but when i open a msstyles msstyleEditor disappear ?

Do you have a fix for me ?

**Comment by nptr** [comment]
you could tell me which style you are trying to open (name, link etc), so i can reproduce the issue and debug the application!

**Comment by nptr** [comment]
open a new issue when you've got more information for me
