### ISSUE TITLE
Make the ribbon menu match the visual style

### ISSUE THREAD

**Issue by VitalSkib** [nptr/msstyleEditor#111]
Hey. 
I wonder if you have plans to also make the msstyleEditor interface dark (as an option)? 
My eyes are not so good lately.. 🫣
tia

**Comment by nptr** [comment]
msstyleEditor is supposed to be rendered according to whatever the active visual style says. It doesn't work properly however because the (3rd party) ribbon control ignores visual styles and i didn't get around to fix it yet.

**Comment by VitalSkib** [comment]
> 

Oh.. 
Yep, I have a dark (Night) custom theme in Windows and it looks like this for me (image below).
 Maybe you can make this ribbon collapsible at least, as in most applications with a ribbon?
 
![msstyleEditor](https://user-images.githubusercontent.com/43848892/224012688-31ca1b9b-6213-46e5-91e0-81b732fdbca5.png)

**Comment by nptr** [comment]
No collapsible ribbon, but i have a test build ready for you that should make the ribbon and dock panels work better with non-light visual styles: [msstyleEditor_test.zip](https://github.com/nptr/msstyleEditor/files/10941464/msstyleEditor_test.zip)

Let me know how it works for you, and if, which UI elements need improvement.

**Comment by VitalSkib** [comment]
> No collapsible ribbon, but i have a test build ready for you that should make the ribbon and dock panels work better with non-light visual styles: [msstyleEditor_test.zip](https://github.com/nptr/msstyleEditor/files/10941464/msstyleEditor_test.zip)
> 
> Let me know how it works for you, and if, which UI elements need improvement.

Oh, it's so cool, now it's completely dark!  😎👍
Thanks a lot! 
As for "which UI elements need improvement", I would change the icons to more modern ones and maybe a custom color choice for the background of the Image View panel,, but this is not a problem at all.. 
Thanks again! 

![msstyleEditor](https://user-images.githubusercontent.com/43848892/224310020-6a85186c-bbac-48db-981c-b2fe96e0e9b9.png)

**Comment by VitalSkib** [comment]
Oh, by the way, any way to save the settings on exit? 
For example, I set the black background color for the Image View panel, and I would like to see this background color at the next launch. 
Instead of changing it every time.. 
Is it possible?

**Comment by nptr** [comment]
Good to hear, thank for testing. I hope to get the changes in the next release. I am not fully pleased yet with the ribbon tabs. Its hard to see the active one. Would you mind posting a screenshot of the "Show controls" dialog, so I can see how a regular tab control would look like with your visual style?

About persisting the settings: Maybe in the future. There are not a lot of options so I chose to delay that task until there is a stronger need. With new features it often is a time and motivation thing.

**Comment by VitalSkib** [comment]
> Would you mind posting a screenshot of the "Show controls" dialog..

Yes, I attached it.. 

> About persisting the settings: Maybe in the future.

Sure, take your time, no problems with this.. 

![Control Preview](https://user-images.githubusercontent.com/43848892/224333687-e591b2a1-a716-435d-a809-a5ca8b8309d4.png)

**Comment by nptr** [comment]
Version [2.0.0.5](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.5) contains the fix to this issue.
Its similar to your test version, but with improved ribbon tab borders. The dockpanel background handling is also
a bit different. That was necessary to get a reasonable look on non-black & non-white visual styles.

I hope this still look well on your system.

**Comment by VitalSkib** [comment]
Yes, it looks a little better. 
Thank you very much for the response.
