### ISSUE TITLE
Changing font from resource string

### ISSUE THREAD

**Issue by migozz** [nptr/msstyleEditor#114]
*Windows Version*: Win7

**Expected behavior**
In version 1.4.0.6, when you select a Font from String table Resources (for example, in TaskBar::Toolbar → Font), there are strings like "501 - Tahoma, 8", and you can select Any string.
In version 2.0.0.5, there's string "501", but without font name in the combobox, and when you open a drop-down list, there are only 7 strings (without numbers), despite the actual number of lines. And when you select a font, instead of a resource number (501) there's displayed a Font Name. And not all "fonts" are available to select.
So it is needed to use older version to change font.

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this

**Comment by nptr** [comment]
I distinguish two cases
* String table missing. msstyleEditor warns here and only displays the resource IDs.
* String table found. msstyleEditor displays the value behind the ID.

| String table missing | String table found |
| - | - |
| ![image](https://user-images.githubusercontent.com/5485569/229288280-cb5f3f53-674d-4adc-b4fc-77cfde7bf8ca.png) | ![image](https://user-images.githubusercontent.com/5485569/229288374-5bc26e6f-47ab-4d4f-a58c-7c8fafc5089d.png)

A third case could be a reference to a non-existing resource. Either ID or string table entry must be wrong in that case. I think i fall back to the resource ID just for this element then. Not sure.

Would any of this explain the problem?

**Comment by migozz** [comment]
My theme: https://drive.google.com/file/d/1qLbQ7ZYBG0ANA9253PF4oKbSg4d3tsA2/view?usp=sharing

Resources:
![reshacker](https://user-images.githubusercontent.com/24635618/229339091-2fc256af-8c47-4a6d-9fa7-74f6e3268ec5.png)

![msstyleeditor1406](https://user-images.githubusercontent.com/24635618/229339102-2150126a-edc8-46de-8648-2059fdf639e7.png)

![msstyleeditor2005](https://user-images.githubusercontent.com/24635618/229339108-6e6c0781-b89e-4804-adc8-e5306a78cacf.png)

So, 501 and 502, 506, 509(?) are not visible, but 503 is visible. But I don't know that it's actually 503 (until I open in old editor).

**Comment by nptr** [comment]
Yep, something is off.  Thanks for sharing the style, that makes troubleshooting easier. l am out of town this week, so a bit more patience is necessary until I can tackle the problem.

**Comment by nptr** [comment]
I found and fixed the bug. The font resource detection was flawed. Fonts without style or quality specifier were not detected as fonts. So "Tahoma, 8" was not considered a font and was subsequently not available in the font selection box.

Use version [2.0.0.6](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.6) to have it working again.
