### ISSUE TITLE
Linux support.

### ISSUE THREAD

**Issue by rokejulianlockhart** [nptr/msstyleEditor#115]
**Is your feature request related to a problem? Please describe.**
* I'm not always at a Windows machine, but still want to be able to edit my styles.
* Occasionally, I use VMs with very little storage, so installing this can be quite an annoyance.
* When using a VM, I usually want to edit the styles on my host system, because I can quite easily share storage between host and VM but not the clipboard always.

**Describe the solution you'd like**
I'd like to be able to run this software natively from Linux.
Considering that this ultimately uses the .NET framework via C#, surely this should be possible?

**Additional context**
Although even more niche, this would also allow me to run it on my Android device. All I need is a vaguely isolated environment with the correct version of gcc, and it'll work, whereas emulation of Windows software is hideous.

**Comment by nptr** [comment]
You _might_ be able to run it with [wine-mono](https://wiki.winehq.org/Mono). I never tried. The "Test" feature will not work of course, WINE doesn't implement the theming engine. Apart from that, I don't see an immediate reason why the rest shouldn't work. Let me know when you tried! Attach screenshots too please.

I have no idea how you want to run it on Android. I never attempted running Windows stuff on Android.

**Comment by nptr** [comment]
OK, i just tried and it kind of runs under WINE / Mono (via Lutris). Its just a bit broken in some places.
![image](https://user-images.githubusercontent.com/5485569/230968795-1d125f8a-40b0-4f0d-8956-80d8a4c1acd0.png)

No idea how much of that is under my control and fixable.

**Comment by nptr** [comment]
I am closing this issue because I won't actively pursue compatibility in this direction. It works well enough as it is. But if someone happens to submit patches I'll consider them of course.

**Comment by rokejulianlockhart** [comment]
It works well with `wine` anyway.

![image](https://user-images.githubusercontent.com/42837531/235324512-78c2eb42-111c-44ed-93a3-64ad456dc3f6.png)
