### ISSUE TITLE
SIZINGMARGINS Right and Top seems to be swapped

### ISSUE THREAD

**Issue by VerMishelb** [nptr/msstyleEditor#120]
*Windows Version*: Windows 10 22H2 19045.2846

In Windows 10's aero.msstyles DWMWindow.BOTTOMFRAME has SIZINGMARGINS of 1;1;0;1 which is being shown as "Left, Top, Right, Bottom" if the item is expanded. However, as it is a bottom frame, the top part is missing, therefore it is the one that has 0 in sizing margins. The struct I got by searching seems to confirm this (https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/ns-uxtheme-margins) (if it's related, of course).
```
typedef struct _MARGINS {
  int cxLeftWidth;
  int cxRightWidth;
  int cyTopHeight;
  int cyBottomHeight;
} MARGINS, *PMARGINS;
```
As another confirmation, top shadow has scaling to left and right, which is 38;38;0;0, which is L;**T**;R;B, while it should be L;**R**;T;B.

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this (could not find)

**Comment by nptr** [comment]
You are correct. Sorry for the inconvenience, i hope it didn't cost you too much time.

I was wrongly assuming the margins to be in L;T;R;B order, possibly because the [RECT structure](https://learn.microsoft.com/en-us/windows/win32/api/windef/ns-windef-rect) actually is. I'll fix it with the next version.

**Comment by nptr** [comment]
[Pre-release 2.0.0.8](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.8) has this fixed. The order in the GUI is still LTRB but you should see the correct values now. `DWMWindow > BOTTOMFRAME > SIZINGMARGINS` is (LTRB) `1;0;1;1` for .
