### ISSUE TITLE
2.0.0.7 seems to have broken Save (w/o MUI) and Test

### ISSUE THREAD

**Issue by VerMishelb** [nptr/msstyleEditor#121]
*Windows Version*: Windows 10 22H2 19045.2846

**Expected behaviour**
Saving (without MUI) and testing the theme, well, works.

**Actual behaviour**
`Updating string resource with id '7' failed with error '1359'` for both cases. "Save with MUI" works though, as far as I can see.

**Additional context**
No editing was done to the theme. "aero.msstyles" was opened in Windows/Resources folder and saved to other place, then opened and the error popped up in attempt to save *this* file. My system language is ru-RU.

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this

**Comment by nptr** [comment]
1. Can it still open and save the one you sent me in issue #91 ? That was for 21H2 ru-RU and it works for me with 2.0.0.7.
2. Would you attach your current one (22H2) aero folder as well?

**Comment by VerMishelb** [comment]
Now that I check again it is saved correctly for both cases. Opening the thing I saved and attempting to save it again throws that error, I worded it incorrectly while I was making an issue. I don't see the point of uploading the themes folder as it hasn't been changed by microsoft since 2019, both .msstyle and .mui files are same on byte level.

**Comment by nptr** [comment]
I was able to reproduce the issue and might have a fix: [msstyleEditor.zip](https://github.com/nptr/msstyleEditor/files/11412483
Let me know.

**Comment by VerMishelb** [comment]
Yup, seems to work now.

**Comment by nptr** [comment]
Same version is now listed as [pre-release 2.0.0.8](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.8). I hope to have it fixed for good. Issue was that msstyleEditor tried to delete a non-existing resource due to broken logic.
