### ISSUE TITLE
Numerical hotkeys to manipulate Image View don't work when Image View has focus

### ISSUE THREAD

**Issue by TiberiumFusion** [nptr/msstyleEditor#123]
*Windows Version*: 6.1.7601.26465

**Expected behavior**
Pressing number keys 1, 2, 3, etc should switch the IMAGEFILE displayed in the Image View when the Image View is focused.

**Actual behavior**
Pressing number keys 1, 2, 3, etc **only** switches the IMAGEFILE displayed in the Image View when an entirely different control has focus - the Class View.

**Additional context**
1. Open any msstyles file.
2. Use the Class View to navigate to an element that has a graphic. For example, `TrayNotifyHorizOpen::Button->Common Properties`.
3. Ensure that the Class View still has the focus.
4. Press keys 1, 2, 3, etc.
Observe that the Image View correctly switches to a display a different IMAGEFILE for the corresponding pressed number key.
5. Click anywhere inside the Image View. The Image View now has the focus.
A practical example of this is simply right clicking the Image View in order to change its background.
6. Press keys 1, 2, 3, etc.
Observe that the Image View does **not** respond. It does **not** switch to display a different IMAGEFILE for the corresponding pressed number key. 

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor (2.0.0.7)
- [x] None of the other issues cover this (afaik, this is not an unambiguous thing to search)

**Comment by nptr** [comment]
Thanks for the report, I see the problem. I even wrote a comment in code saying "very hacky". Never got to doing it properly. Next version will have it fixed.
