### ISSUE TITLE
How to theming "home" and ribbon in Windows 11's new file explorer

### ISSUE THREAD

**Issue by KrazyLurt** [nptr/msstyleEditor#132]
*Windows Version*: Windows 11 beta , build 2231.2338

**Question**
The new Windows 11 file explorer available in beta and upwards have an issue using my custom theme where the ItemsView color aren't applied in "home" and also I'm not sure how to edit the background color if the ribbon using msstyleeditor.

Is there a way to edit my theme with msstyleeditor for the "home" to use my set ItemsView bg color? And the same for the ribbon.

**Checklist**
- [x ] My uxtheme.dll is patched
- [ x] I am using the latest version of msstyleEditor
- [x ] I checked the Wiki
- [ x] None of the other issues cover this

**Comment by nptr** [comment]
I have no idea, and also don't use W11 to see for myself.
You will have to ask on the various customizing boards.

If you figure it out, let know.
