### ISSUE TITLE
How to change the color of a windows element?

### ISSUE THREAD

**Issue by Lipton323** [nptr/msstyleEditor#136]
WIN 11 21H2

Good day. I want to change the color of the element, a screenshot of which I will attach below. How do I do this using msstyles? I need to change the color of the selected element, that is, in this case, the GTA folder. This is the dark purple color.
https://imgur.com/a/tUTusL7

I tried to run the .msstyles file in the program, I found the color by searching, but replacing it does not lead to anything. And yes, this color was found only once, there are no more items with it.

- [ yes] My uxtheme.dll is patched
- [yes ] I am using the latest version of msstyleEditor
- [ yes] I checked the Wiki
- [yes ] None of the other issues cover this

**Comment by nptr** [comment]
Sorry for the late response!

The item selection in the explorers list view is determined by `Explorer::ListView` > `LISTITEM` as far as i remember. Its a small transparent icon that is resized and rendered onto the selected item (Image property + sizing properties). It's not a simple color property!

The folder icon itself is a resource inside 
- C:\Windows\SystemResources\shell32.dll.mun (Win10 and after)
- C:\Windows\System32\shell32.dll.mun (before Win10)
Replacing that is not a job for msstyleEditor but for [ResourceHacker](https://www.angusj.com/resourcehacker/).
