### ISSUE TITLE
The search feature is hidden

### ISSUE THREAD

**Issue by ks74** [nptr/msstyleEditor#14]
One more thing. I read about the search feature, but could not find it. I accidentally read about it later and found out one has to press Ctrl-F to activate it. You should add a menu item for the feature or hint about it somehow, otherwise it's kind of hidden. 
The same applies to the background change function. Unless one right clicks the image area, they are unlikely to find the function. 

Also, I could not find the classes "Window" and "Button" - at first. Somehow, I tried again and then it started working. I could find everything. So, sometimes search just does not work, and sometimes it does and in order to make it work I have to do some fake activity.
Also, Esc should close the find dialog and the dialog should have a button to start searching.

**Comment by nptr** [comment]
I'll consider putting these options in the menubar as well for the nect version!
Regarding "could not find the classes":
* maybe you selected "Property" in the search window?
* the search will find the next occurence. if there are multiple, you will have to search again.
Intended workflow: Ctrl+F, type "window", press enter/click the search button until you found the entry. The treeview should jump to the found item on every press/click.

**Comment by ks74** [comment]
I did not select property, but I can't reproduce it now when I want it, but yesterday I had the problem again. Somehow it didn't find anything at all. Then I selected property and then again class/part and then it started working.

**Comment by nptr** [comment]
Added menu entries for said options in V1.4.0.0 along with their shortcuts (if available).
