### ISSUE TITLE
UNKNOWN_5100_COLORLIST and 5101 property addition

### ISSUE THREAD

**Issue by TrantaLocked** [nptr/msstyleEditor#141]
**Is your feature request related to a problem? Please describe.**
I am trying to modify a style to have a solid color Menu bar, but styles without UNKNOWN_5100_COLORLIST already added to them are forced to have a white border regardless of how any color properties are changed (including BORDERFILL),

**Describe the solution you'd like**
I would like to be able to manually add the UNKNOWN_5100_COLORLIST Collection property to control the Menu bar border line colors.

**Describe alternatives you've considered**
I believe this is the only way to control the border color but there could be other ways.

**Additional context**
![FRFFR](https://github.com/nptr/msstyleEditor/assets/18237916/c4fa3226-3f2e-42c5-8cbe-37ba71e17cc2)

The border stays white when editing Menu color properties for non-Aerolite theme. UNKNOWN_5100_COLORLIST and and UNKNOWN_5101_COLORLIST are found in the Aerolite msstyle under Menu -> BARBACKGROUND. Colors 0 and 2 in 5100 Colorlist allow editing of the Menu bar border color while colors 1 and 3 control fill color.

I would appreciate help in finding an existing property that does same thing!

**Comment by nptr** [comment]
Hi, sorry for late response. With the attached test version you should be able to add those properties: [msstyleEditor_issue141.zip](https://github.com/user-attachments/files/15744370/msstyleEditor_issue141.zip)
The next proper release will include this too, but I wouldn't want you waiting any longer!

Great that you figured out the effect of those properties and the individual color entries. This is not widely known i think?
Please let me know about any other findings around those properties. I can then add this to my [Wiki](https://github.com/nptr/msstyleEditor/wiki/Introduction), or maybe even come up
with a sensible name for these unknown properties.

**Comment by nptr** [comment]
[Version 2.1.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.0.0) includes the feature described, so am closing this issue now. Feel free to reopen it in case something still doesn't quite work.
