### ISSUE TITLE
"Deleting string resource with id '33' failed with error '87' prevents me from saving skin or testing

### ISSUE THREAD

**Issue by 1winn1** [nptr/msstyleEditor#142]
*Windows Version*: Win 10 20h1

**Question**
It doesnt matter the skin I use or whether I change anything or not, as soon as I hit test or save I get an error message saying 
"Deleting string resource with id '33' failed with error '87'
what does this error message mean and how can I fix it? I can't seem to find information about error codes

**Things you already tried**
I tried searching for said object with id '33' but when I go to the search button, under the 'filename' searching category it cant find any object via id no matter the number I input.

**Additional context**
* The theme I'm trying to change is Bouquet by niivu

**Checklist**
- [yes ] My uxtheme.dll is patched
- [yes ] I am using the latest version of msstyleEditor
- [yes ] I checked the Wiki
- [ yes] None of the other issues cover this

**Comment by nptr** [comment]
Unfortunately this is a known issue to which i haven't found a solution yet :(
You can read more here: [https://github.com/nptr/msstyleEditor/issues/126](https://github.com/nptr/msstyleEditor/issues/126)

I'll let you know if i make progress on this.

**Comment by 1winn1** [comment]
Thanks for the reply, I'll try the work around you suggested.
please let me know whenever you fix the bug!

**Comment by nptr** [comment]
See if the version i uploaded in issue #146 fixes the problem!
If it does, the next proper release will have this fix included.

**Comment by nptr** [comment]
[Version 2.1.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.0.0) includes the fix to this problem, so am closing this issue now. Feel free to reopen it in case something still doesn't quite work.
