### ISSUE TITLE
Weird Color

### ISSUE THREAD

**Issue by 0xJWLabs** [nptr/msstyleEditor#149]
*Windows Version*: Win11

**Question**
Hey, I don't know what is this called, but how to fix these, thanks!
![Screenshot (17)](https://github.com/user-attachments/assets/80f4de80-e171-4b95-a343-8f798a6799e0)
![Screenshot (16)](https://github.com/user-attachments/assets/001798d7-6e55-41ce-ab68-b82ee0351ca2)

**Comment by nptr** [comment]
I can only guess what "these" are. I see the following:

1. Browser Window - Dark text on dark background, which is barely readable. Doesn't seem like a visual style issue. The browser content is rendered by browser itself, using the style sheets and HTML from the webpage. Maybe you have some dark mode addon installed in your browser that messes up the visibilty. Or linkedin itself is broken.
2. MsstyleEditor - Clashing gray text and pastel green background. Probably a visual style issue. I suggest to see whats set in the `TreeView` class.

Good luck!
