### ISSUE TITLE
Multiline edit under Control Preview dialog

### ISSUE THREAD

**Issue by CodeVisio** [nptr/msstyleEditor#150]
Hi,

As from the title, why there is no multiline edit ccontrol, as an example with theme applied, on the Control Preview dialog?

Thanks

**Comment by nptr** [comment]
No particular reason. Maybe I forgot. Maybe I thought the regular edit control is sufficient. Multiline edit control is the same control as the regular single line text box i think. Just a bit different behaviour. Altough now you made me unsure.

Does single-line/multi-line make a difference? And where?

**Comment by CodeVisio** [comment]
>  Multiline edit control is the same control as the regular single line text box i think. Just a bit different behaviour.

I think so. There is no Win32 class for multiline edit control (it's the same as for single line),
but do they have different behavious. The only difference is a style bit.

>Does single-line/multi-line make a difference? And where?

That's my point I was curios of. At theme level, do they use the same partid? And EDITBORDER_*SCROLL play a role here?

A single line edit control can have autoscroll or not, but it has no horizontal bar, while multiline can have no bars, one of them or both.

Thanks

**Comment by nptr** [comment]
I don't have any deeper knowledge than you already have, sorry.

> At theme level, do they use the same partid? And EDITBORDER_*SCROLL play a role here?

They are using the same class "Edit", and depending on the style set (ES_PASSWORD, ES_MULTILINE) will query some properties from the PASSWORD or EDITBORDER_*SCROLL parts. Now that you are mentioning it, yes the EDITBORDER_NOSCROLL is likely used for single, while the others can be used for multiline. And they could look different. But in practice that doesn't seem to be the case. So my solution is still good i think 😄 

The scrollbars themselves are just the Win32 scrollbars ("ScrollBar" class). I am displaying them separately rather then in Edit/Tree/List controls.

**Comment by CodeVisio** [comment]
You are likely to be right but,
it is still not clear which partid is used for single edit (autoscroll or not) and multiline edit (no scroll, horz scroll, vert scroll, and both).
E.g. a single edit with autoscroll style bit has the EDITTEXT partid or the EDITBORDER_HSCROLL partid?
Or a single edit with no autosccroll style bit has the EDITTEXT partid or the EDITBORDER_NOSCROLL?

**Comment by nptr** [comment]
A control doesn't have to use just one part. It can use multiple parts and query values dynamically. See for example the [`GetThemeColor()`](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemecolor) function, which takes `iPartId`, `iStateId` and an `iPropId` as arguments. Between controls and classes there is a much closer relationship, as thats the "key" into the theme data structure (see [`OpenThemeData()`](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-openthemedata) ).

What exactly a single line non-scrolling edit control uses, I don't know. Probably "Common", EDITTEXT, BACKGROUND, EDITBORDER_NOSCROLL. One can maybe find out using [APIMonitor](http://www.rohitab.com/apimonitor) or some other API tracing tool.
