### ISSUE TITLE
Separator line in Explorer, how to change color

### ISSUE THREAD

**Issue by Mira-Bellenbaum** [nptr/msstyleEditor#159]
*Windows Version*: <<Win7, Win 10 1703, Win 10 1809, ...>>

**Question**
In Explorer, there is a dividing line between the scrollbar and the file window. Where and how can I change its color?

**Comment by nptr** [comment]
Unfortunately I don't know, Screenshots always help tho!
There is a also _very_ simple [Wiki](https://github.com/nptr/msstyleEditor/wiki/Explorer), maybe that points you in the right direction?

**Comment by Mira-Bellenbaum** [comment]
Oh, danke für die Antwort, Problem ist aber gelöst. 
Oh, thanks for the answer, but the problem is solved.  :D
