### ISSUE TITLE
Possible suggestion on msstyles reverse engineering

### ISSUE THREAD

**Issue by antiufo** [nptr/msstyleEditor#16]
I just wanted to point out that it should be possible to extract the struct definitions for msstyles files from the public debugging symbols of uxtheme.dll, as reported in this [thread](http://winclassic.boards.net/thread/181/modifying-msstyles-get-classic-theme).

Anyways, awesome project!

**Comment by nptr** [comment]
Hello, glad you like it and thanks for the info! :)

I do actually use the debug symbols you are mentioning, I even had a short
conversation with "IbmPad", the person mentioned in the thread.

This was however not so long ago and I already had the most important things figured out.
Nonetheless it helped to clarify a few things.

- nptr
