### ISSUE TITLE
How to import/export properties

### ISSUE THREAD

**Issue by Za9-118** [nptr/msstyleEditor#164]
*Windows Version*: Win 11

**Question**
How do i export a Part and import it to another theme?

**Things you already tried**
What have you already tried to solve the problem?

**Additional context**
Everything you think helps understanding the question or problem.
* The theme im exporting the part from is Aero10 Vista by vaporvance
* Screenshots: 
![Screenshot 2024-12-12 204523](https://github.com/user-attachments/assets/3ae43b6b-6390-4341-90be-426a0cb884f2)
![Screenshot 2024-12-12 204613](https://github.com/user-attachments/assets/08edcf0d-0366-4133-a625-b6b5938b1532)
* Properties from one theme are imported to another one

**Checklist**
- [ ? ] My uxtheme.dll is patched (Im using SecureUX)
- [ Y ] I am using the latest version of msstyleEditor 
- [ Y ] I checked the Wiki
- [ Y ] None of the other issues cover this

(Y=yes, N=no i dont know how to use these sorry)

**Comment by nptr** [comment]
Hi, unfortunately I haven't implemented that yet. Sorry for giving a false impression here. It has been on my list for quite some while (see issue #77 and #104), but never found the time to properly do it.

**Comment by Za9-118** [comment]
You liar >:3 (Just kidding, you're awesome)

**Comment by nptr** [comment]
Thanks :) I am closing this issue as duplicate to have a concise list, and will track any progress in the older issues. With the release notifications you should be informed when something changes.
