### ISSUE TITLE
Virus detection by Microsoft Edge and Windows (v2.1.1.0)

### ISSUE THREAD

**Issue by avidichard** [nptr/msstyleEditor#166]
Microsoft Edge refuses to download the latest release because it sees a virus. Windows does not permit me to extract the zip I downloaded using Firefox because Windows sees a virus too. This is not the case for 2.1.0.1.

I don't know what changed in the executable but Microsoft does not like it.

**Comment by nptr** [comment]
Looks like their heuristic guessed wrong. Here is a [scan of 2.1.1.1](https://www.virustotal.com/gui/file/dc655ccf9d6c6742cf02fc6ef64d435e6781a7c723d82f9c52cc631c107edb58) and 69/70 anti virus are fine with the file. Funny enough, the one that is complaining is not Microsoft but some obscure one.

The latest version does more file I/O, specifically in the temp directory, for [this feature](https://github.com/nptr/msstyleEditor/issues/108). Maybe that's throwing it off.

You'll have to whitelist it for now, possibly report it as false positive if your software allows for that too. And getting rid of MS Edge is positive anyways 😅

**Comment by avidichard** [comment]
Are you already working on v2.1.1.1?
![2024-12-17 19_27_13-CompatWindow](https://github.com/user-attachments/assets/e6e87ca2-6d78-4629-9176-3333e85b78c3)
I just think it's an email error LOL. Anyways, I know people are not all too keen on Edge but it's the browser that uses the least memory and works the fastest. I was a fervant Firefox User until it started to behave slow and when the stopped letting me re-arrange the title bar as I wanted. I had 1 single bar which contained address bar and tabs which gave me more screen space. The only thing I loved about Firefox was the very generous customizing, now, it just joined everyone else with their style. I also tried the gaming browser Opera GX, but it does not let you define your startup page, I just utterly hate the new startup page, when I open a browser, I want Google to open or whatever other homepage I defined, not another interface proposing me another background and some other shortcuts, I have Windows Desktop and Start Menu for that.

Anyways, I think this was unrelated, just had to get some steam off my once past browser misery. so, to continue...

Windows' own anti-virus is blocking, I have no anti-virus installed on my computer so I guess I'll need to whitelist your app. But I still think that some basic operations like the ones you do are maybe detected as potentially dangerous and there's amybe a workaround to to prevent anti-virus apps from detecting such NON-threats.

When linux will be able to run GameMaker Studio 2 and Hydro Thunder Hurricane as well as Steam games such as Skyrim Anniversary, Cyberpunk and others as well as run .Net framework dependant apps, I'll probably make the move there. For now, I'm comfy with my win11 setup and happy with your app too.

I also do not know that AntiVirus in the list you submitted so, I guess MS is just MS. Nothing else to say your honor!

**Comment by avidichard** [comment]
Well, well, well, would you see that, MS Edge downloaded it today and Windows permitted me to extract the zip just as I finished my previous message. This annouces a close since I did not do anything yet, no whitelist, nothing, so maybe a AV database update happened. Anyways, thanks again for your quick response!!!

**Comment by nptr** [comment]
Haha good to hear, and no offence taken :)

The version 2.1.1.1 was a typo which I corrected only after the notification from github went out.
