### ISSUE TITLE
Simplify compilation process

### ISSUE THREAD

**Issue by Syth-1** [nptr/msstyleEditor#18]
so i downloaded the files - saw there was an .sln file so i ran that opening visual studio, pressed build and error. . . fair enough. 

so i click run last successful build, more errors, 
so what exactly am i suppose to run, i feel rlly dumb founded atm ;-;

**Comment by nptr** [comment]
Hi,
i used the wxWidgets library to create the UI, but that has to be separately downloaded and compiled.
You can find a short description on how to build [here](https://github.com/nptr/msstyleEditor/wiki/How-to-build). It assumes basic knowledge of Visual Studio and C++ so it's not very detailed,

Recently i began switching to WTL, to make the application more leightweight and easier to compile.
You can find my results in the "wtl-spinoff" branch: https://github.com/nptr/msstyleEditor/tree/wtl_spinoff
It requires to download [WTL](https://sourceforge.net/projects/wtl/) and installing it. Maybe adjusting the additional include directories of the "msstyleEditorWTL" project so WTL is found. But no separate compilation or linking steps.

-- nptr

**Comment by nptr** [comment]
I rewrote msstyleEditor in C#. Compiling is now pretty easy and any developer should be able to. A matter of a single button press in Visual Studio. No dependencies to be (manually) downloaded, compiled or configured. I guess that concludes this task.
