### ISSUE TITLE
Error message when saving styles with a missing image file

### ISSUE THREAD

**Issue by ks74** [nptr/msstyleEditor#19]
Hello. When I save styles after (mistaken) removing an image file that I replaced an image with, the msstyleEditor displays an error that does not explain what happened. At least, it should say what file name is missing and for what node it is used. 
Also, if I try to save styles to the same file, msstyleEditor displays an error message with errorcode 100. The idea not to change the original file in itself is good, but the error message should be more explaining. At least, it should say that one cannot save a file to itself or something like that.

**Comment by nptr** [comment]
Good find, thanks! I fixed it!
When more fixes and improvements accumulated, I'll make a new release.

**Comment by ks74** [comment]
Oh, I forgot one more thing. In the first scenario, if I replace an image and then delete/rename the image file, and then I return to the imagefile node where I replaced the image in the styles (so that the application rereads the image file from disk), the application just halts (Windows displays an error message about it).

**Comment by ks74** [comment]
Great!

**Comment by nptr** [comment]
Fix is included with V1.4.0.0
