### ISSUE TITLE
Path with cyrillic symbols cause "bad conversion" error

### ISSUE THREAD

**Issue by SigmaTel71** [nptr/msstyleEditor#21]
If you put your .msstyles folder which has cyrillic symbols in its name, you will get "bad conversion" error if you try to open the file from there.
![image](https://user-images.githubusercontent.com/17989678/52295794-b9739c80-298d-11e9-9e6f-7360f643683d.png)
For example, I have named my folder as "тест" ("test" in English). If I open the file from folder without cyrillic symbols, which is "test" in this case, it will open normally. If I try to do this in "тест" folder, which has cyrillic symbols, I'll get the error message as above on the screenshot.

**Comment by nptr** [comment]
Thanks for reporting this bug! The next version will have this fixed!
