### ISSUE TITLE
"Find" window has strange look on 125% scaling

### ISSUE THREAD

**Issue by SigmaTel71** [nptr/msstyleEditor#24]
![image](https://user-images.githubusercontent.com/17989678/53288200-e77f1c00-3796-11e9-98bd-8b591ca79dbe.png)
Self-explanatory. I can't even see a thing.

**Comment by nptr** [comment]
Thanks for testing, i'll fix it today! Is the path issue (#21) fix working at least? :)

**Comment by SigmaTel71** [comment]
> Is the path issue (#21) fix working at least? :)

![image](https://user-images.githubusercontent.com/17989678/53289472-5cf2e880-37a7-11e9-8e2c-ba2839d7c932.png)
Yep! "Барахло" means "Stuff". :grinning:

**Comment by SigmaTel71** [comment]
![image](https://user-images.githubusercontent.com/17989678/53289495-b3602700-37a7-11e9-8a9a-97ed733f183f.png)
v1.4.0.1 fixed the issue #24.
