### ISSUE TITLE
OS rejects theme if I try to test it

### ISSUE THREAD

**Issue by SigmaTel71** [nptr/msstyleEditor#25]
![image](https://user-images.githubusercontent.com/17989678/53291076-a7339400-37be-11e9-854e-3c658edd3b14.png)
I have only replaced TreeItem's glyphs and got this error. Same thing happens if I "feed" vanila .msstyles file to the editor.

**Comment by nptr** [comment]
Are you testing the theme on the respective OS?
Is your theme engine (still) patched?
Do other 3rd party styles work? (applied via windows)
Do other 3rd party styles work? (applied from inside the editor)

You could also send me the original and the modified version. Maybe i can spot something
by running a binary diff tool on it.

**Comment by SigmaTel71** [comment]
> Are you testing the theme on the respective OS?

Yes, I'm editing on Windows 8.1 with all security updates installed.

> Is your theme engine (still) patched?

Yes, they work.

> Do other 3rd party styles work? (applied via windows)

After Dark Blue CC, which I have installed, works without any issues.


> Do other 3rd party styles work? (applied from inside the editor)

I can't even open theme mentioned above (look on the screenshot below)
![image](https://user-images.githubusercontent.com/17989678/53297020-32953f80-3828-11e9-91dd-613caf230b7e.png)

**Comment by SigmaTel71** [comment]
> You could also send me the original (working at least when applied via windows) and the modified (not working) version. Maybe i can spot something by running a binary diff tool on it.

Original and modified .msstyles files don't work inside the editor. I'm dropping here two files: original aero.msstyles and treetest.msstyles.

[aero+treetest.zip](https://github.com/nptr/msstyleEditor/files/2897733/aero%2Btreetest.zip)

**Comment by SigmaTel71** [comment]
Problem resolved after ``sfc /scannow`` running through the system and reapplying theme engine patch.

**Comment by nptr** [comment]
Thats weird because I just fixed those issues ;)
* for treetest.msstyles the editor didn't take over the original language; maybe a reason why it didn't work in the first place
* the "Bad property" message occured because I couldn't handle empty INTLIST properties

Why the original aero didn't work is a mistery though.. Maybe there is some theme cache and one of the styles corrupted it. I could further guess that either sfc helped or it was just the reboot.

**Comment by SigmaTel71** [comment]
> Thats weird because I just fixed those issues with [V 1.4.0.2](https://github.com/nptr/msstyleEditor/releases/tag/1.4.0.2) ;)

Fixing confirmed, closing the issue! :wink:
