### ISSUE TITLE
Caption round corner

### ISSUE THREAD

**Issue by DwordXor** [nptr/msstyleEditor#28]
Hello 

your editor is very nice i have a little problem
how i can create round cornor on a caption top and bottom 

https://i.postimg.cc/L5PwLNKm/Unbenannt.png

Greets,

**Comment by SigmaTel71** [comment]
Try editing respected PNG file and remove these pixels to create transparent area.

**Comment by DwordXor** [comment]
How i can make this Transparent? any settings?

**Comment by SigmaTel71** [comment]
> How i can make this Transparent? any settings?

Use Adobe Photoshop or paint.NET to edit PNG files.
