### ISSUE TITLE
A humble suggestion...

### ISSUE THREAD

**Issue by yahavatar** [nptr/msstyleEditor#3]
If there was a way to export all settings to a text/xml/csv file, that would allow one to compare different styles in a logical manner. I thank you for the tool it is quite useful!

**Comment by nptr** [comment]
Glad to hear :) I will consider your suggestion in future releases!

**Comment by nptr** [comment]
[Version 1.2.3.0](https://github.com/nptr/msstyleEditor/releases/tag/1.2.3.0) includes such a feature now.
It was quite useful for debugging purposes i have to say :)
