### ISSUE TITLE
msstyles files fail to open

### ISSUE THREAD

**Issue by picant** [nptr/msstyleEditor#30]
Can't open any msstyles file downloaded from http://www.skin-soft.co.uk/VisualStyles/Skingallery.aspx Get an error "Are you sure this is a Windows Vista, 7, 8 or 10 visual style? Details: Style contains no class map!" I use those files to load into a different skin editor and they load just fine there. I tried carbonp3, cosmo, ex2008 and lakrits files.

**Comment by nptr** [comment]
Thats because those are Visual Styles for Windows XP, which I do not support.

**Comment by picant** [comment]
This particular msstyle format is not supported
