### ISSUE TITLE
White Text Color on buttons in Firefox

### ISSUE THREAD

**Issue by Goujer** [nptr/msstyleEditor#33]
I thought this was a change that I had made but I was also able to reproduce it with Windows 8.1's stock aero.msstyles via the Theme Tester, so I figured it was related to this.
Basically all you have to do is download a file, such as this project, and the selected OK/Cancel button will have white text instead of black. You can also see this with Closing Multiple Tabs warning's OK and Cancel Buttons.
I've only been able to find this in Firefox, and I suspect it might be something beyond the scope of this project.
I thought I saw it once in Notepad++ as well though. I'll keep an eye out, but it may have been a Firefox dialog on-top of Notepad++.

I don't mean to bother you but as this seems to be potentially related to the application itself.

**Comment by ks74** [comment]
Look here
https://bugzilla.mozilla.org/show_bug.cgi?id=1518018

**Comment by Legojer** [comment]
I figured.
I discovered that the Windows 8 Developer Preview's .msstyles's DWMTouch has a different mapping for parts then Windows 8.
I've mapped out the part number to their equivalents in Windows 8.1. Is this something I should send you? 
How would you like me to send it?

**Comment by ks74** [comment]
Has is fixed the problem with Firefox for you?

**Comment by Legojer** [comment]
No.

**Comment by ks74** [comment]
Then I don't see why you want to send something.

**Comment by Goujer** [comment]
@nptr mentioned in #32 that he was looking for the use of unnamed parts.

**Comment by nptr** [comment]
@Goujer sure, i'm happy for any help i can get :) Either post your mapping here, attach it, or send me an email :)

@ks74 Great find and thanks for moderating!

**Comment by Goujer** [comment]
Here is DWMTouch's mappings in Windows 8 Developer Preview with their equivalents in 8.1msstyle.
There are direct conflicts with Windows 8 however though.
Might be better to just not worry about it.

DWMTouch Windows 8 Developer Preview
	Part1	= DWMTouch.TOUCHDRAG
	Part2	= DWMTouch.TOUCHCONTACT
	Part3	= DWMTouch.TETHER
	Part4	= It's a circle
	Part5	= DWMPen.PENHOLD
	Part6	= DWMPen.PENRIGHTTAP
	Part7	= DWNPen.PENTAP
	Part8	= DWMPen.PENDOUBLETAP
	Part9	= DWMPen.FLICKSCROLLUP
	Part10	= DWMPen.FLICKSCROLLDOWN
	Part11	= DWMPen.FLICKDRAGUP
	Part12	= DWMPen.FLICKDRAGDOWN
	Part13	= DWMPen.FLICKFORWARD
	Part14	= DWMPen.FLICKBACKWARD
	Part15	= DWMPen.FLICKCUT
	Part16	= DWMPen.FLICKCOPY
	Part17	= DWMPen.FLICKPASTE
	Part18	= DWMPen.FLICKUNDO
	Part19	= DWMPen.FLICKREDO
	Part20	= DWMPen.FLICKPRINT
	Part21	= DWMPen.FLICKDELETE
	Part22	= DWMPen.FLICKOPEN
	Part23	= DWMPen.FLICKSAVE
	Part24	= DWMPen.FLICKMODIFIERKEY
	Part25	= DWMPen.FLICKSHIFTKEY
	Part26	= DWMPen.FLICKWINKEY
	Part27	= DWMPen.FLICKGENERICKEY
	Part28	= DWMTouch.TOUCHDOUBLECONTACT
	Part29	= DWMTouch.TOUCHCONTACTPRESENTATIONMODE
	Part30	= DWMTouch.INDIRECTTOUCH

**Comment by nptr** [comment]
You are probably right. I won't make efforts to support Win8 Dev Previews. Its too much of a niche version. Peculiarities in future Windows (10) versions, sure, but not Win8. Still good to have that information available!
