### ISSUE TITLE
Windows 8.1 CommandModule/LIBRARYPANEIDENTIFIER is actually LIBRARYPANEBACKGROUND

### ISSUE THREAD

**Issue by Goujer** [nptr/msstyleEditor#34]
It would appear that between Vista, 7 and 8.1 the parts for CommandModule have changed.
This can be seen when doing a direct comparison between Windows 8.1, 7 and Vista's aero.msstyles.

Windows Vista
MODULEBACKGROUNDCOLORS is TASKBUTTON
TASKBUTTON is SPLITBUTTONLEFT
SPLITBUTTONLEFT is SPLITBUTTONRIGHT
SPLITBUTTONRIGHT is MENUGLYPH
MENUGLYPH is OVERFLOWGLYPH

Windows 8.1
LIBRARYPANEIDENTIFIER is actually LIBRARYPANEBACKGROUND

**Comment by nptr** [comment]
It should be better now, see [pre-release V 1.4.0.5](https://github.com/nptr/msstyleEditor/releases/tag/1.4.0.5)
