### ISSUE TITLE
Cannot add HIGHCONTRASTCOLORTYPE properties

### ISSUE THREAD

**Issue by phd-hub** [nptr/msstyleEditor#36]
Sample text output includes:
		State: PROGRESSBAR
			Prop FILLCOLOR (COLOR) (229, 229, 229)
			Prop TEXTCOLOR (COLOR) (35, 151, 201)
			Prop FILLCOLOR_HIGHCONTRAST (HIGHCONTRASTCOLORTYPE) (BTNFACE)
			Prop TEXTCOLOR_HIGHCONTRAST (HIGHCONTRASTCOLORTYPE) (BTNTEXT)

Trying to copy these properties to another style, I cannot add the HIGHCONTRASTCOLORTYPE property.

**Comment by nptr** [comment]
Yes, HIGHCONTRASTCOLORTYPE props can't be added at the moment.
I simply didn't implement it yet. Sorry. Next release!

**Comment by phd-hub** [comment]
Do you have an ETA on when a new version might be released?

**Comment by nptr** [comment]
It should be better now, see [pre-release V 1.4.0.5](https://github.com/nptr/msstyleEditor/releases/tag/1.4.0.5)

I support a few more prop types (FILENAME aka. Images, SIZE & HIGHCONTRASTCOLOR), but its still not complete... Missing DISKSTREAM = ImageAtlas, RECT, FONT, INTLIST, FLOAT, FLOATLIST to name a few. Also adding/removing FILENAME is a bit buggy as I don't update the class view nor the image view. Saving and reloading helps tho.

**Comment by phd-hub** [comment]
Many thanks :)
