### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by andybot89** [nptr/msstyleEditor#39]
which file to i open to use the program? there doesn't appear to be an EXE file.

**Comment by nptr** [comment]
You usually don't check in binaries into version control.
Find them here: https://github.com/nptr/msstyleEditor/releases
There is a menu item for it as well:
![grafik](https://user-images.githubusercontent.com/5485569/77566863-90caa100-6ec6-11ea-9457-9a64399c8349.png)
