### ISSUE TITLE
Cant Find PopupItem Hot

### ISSUE THREAD

**Issue by J-e-r-e-m-i-a-h** [nptr/msstyleEditor#4]
Trying to find PopupItem Hot (that's the name in Win7 Style Builder) but I can't :( I just want to change the highlighting image of the context menu (like when you right-click your desktop) but I've looked through what feels like the entire menu.

**Comment by nptr** [comment]
Not sure what your style looks like, but it's right there for me...
I could also find it through the search menu (Ctrl+F).

![menuitemlocation](https://user-images.githubusercontent.com/5485569/30654296-c3c6607e-9e2d-11e7-91c5-b15a73b7da6d.png)

In case this image doesn't help, you can attach the style and i'll have a look at it.

**Comment by J-e-r-e-m-i-a-h** [comment]
![image](https://user-images.githubusercontent.com/31524381/30664427-8d3d6730-9e02-11e7-831d-f4d4087dcdf4.png)

[After Dark Blue4.zip](https://github.com/nptr/msstyleEditor/files/1319032/After.Dark.Blue4.zip)
(it's not actually a zip, just rename the extension. they dont allow msstyles)

**Comment by nptr** [comment]
Thanks for the file.. The "Menu" entry is indeed in the style, but the program didn't manage to find it, as the layout differs a bit from other styles i have tested. I'll make a patch and release a fixed version shortly, stay tuned ;)

**Comment by J-e-r-e-m-i-a-h** [comment]
awesome, thanks

is there a way to add a property? changing an object to an image file doesn't display the option to change the sizing type to stretch or sizing margins (normally you'd have to add the property)

**Comment by nptr** [comment]
Unfortunately not. Currently its more or less a hex editor with a user interface designed for visual styles. I have not yet experimented with rebuilding the styles structure (adding, removing things) as my own use cases didn't demand it. Maybe its open source nature helps to progress a bit :)

**Comment by nptr** [comment]
[Version 1.2.3.0](https://github.com/nptr/msstyleEditor/releases/tag/1.2.3.0) features the improved property detection from the quickfix-release along with other improvements.
