### ISSUE TITLE
Save as/open dialog background 

### ISSUE THREAD

**Issue by innuendo33** [nptr/msstyleEditor#42]
Hi 

Could you help me find this location ? ( the bottom part of save as / open dialog ) I can't seem to find with your editor where to change color of bckground there 
https://imgur.com/a/ZnQnizE

Thanks for help

**Comment by nptr** [comment]
Sorry, I currently have limited access to my computer, so just a short response:

The part in question seems to be the background of the dialog window.
Maybe the `Window `class helps. I suggest searching for the exact color you are seeing. Then
change every occurence to something flashy so you can then find which one had an effect.
