### ISSUE TITLE
Classic Theme for Windows 10

### ISSUE THREAD

**Issue by malvinas2** [nptr/msstyleEditor#44]
To whom it may interest: 
A classic theme for Windows 10
[https://github.com/malvinas2/ClassicThemeForWindows10](https://github.com/malvinas2/ClassicThemeForWindows10)
Created -among others- with MSStyle Editor ;-)

**Comment by nptr** [comment]
Oh, great! Always good to see where my app was used :)

How come the min/max/close button is so huge and still Win10-ish?
Personal preference or doesn't Win10 play nice?

**Comment by malvinas2** [comment]
Actually it is a relict from the Win 8 theme, which served as a basis.

**Comment by malvinas2** [comment]
In case someone finds solutions to the still existing problems described in the issues section of ClassicTheme, I would be grateful if you would inform me.
