### ISSUE TITLE
References for Visual Styles ? 

### ISSUE THREAD

**Issue by malvinas2** [nptr/msstyleEditor#45]
Does anyone know a reference describing the format, which the visual styles are using ? 
I just know [https://docs.microsoft.com/en-us/windows/win32/controls/themes-overview](https://docs.microsoft.com/en-us/windows/win32/controls/themes-overview) but it doesn't describe the differences between the whole Windows 10 versions.

**Comment by nptr** [comment]
Hello again :)

Visual styles are more or less undocumented. The documentation tree you found is pretty much the only thing from MS and its
largely incomplete. There are no references for designers. Custom styles were never really intended. The designers at Microsoft are much better at this as we all saw with the disasters called Windows 8 & Metro UI.

And unfortunately I know of no 3rd party site either. I guess you are left with collecting aero.msstyles of all the versions and attempting it yourself; using the few tools available. I'd be interested in the styles as well as the results.

For the msstyleEditor, I did this on a technical level for the Windows generations (Vista, 7, 8, 10), but have yet to consider the "new" YYMM versioning scheme.

Good Luck!

**Comment by malvinas2** [comment]
Schreib' mir doch mal eine Mail ;-)

**Comment by nptr** [comment]
I did. And best check your spam filter ;)
