### ISSUE TITLE
OS rejects style in some cases

### ISSUE THREAD

**Issue by nptr** [nptr/msstyleEditor#48]
It was reported that while applying the style works now most of the time, in some cases it still fails.
One case is the default aero theme in an unspecified Win10 versions (see issue #29, one of the last comments).

This issue has the purpose to collect and track those cases so I don't forget.

**Comment by dt192** [comment]
@nptr If you need anything testing in win10 regarding this issue or anything else, just @ me.

**Comment by nptr** [comment]
Will do, thanks!

**Comment by depascalis** [comment]
I just tried this tool and immediately ran in to this issue. 

**Reproduce**
1. Open any `.msstyles` from `%winddir%\Resources\Themes`, 
2. Test the style
3. Modify and test the style

**Result**
Failed to apply the theme as the OS rejected it!
SetSystemVisualStyle() returned 0x90070490

**System**
Windows 10 Pro 21H1 19043.1237

**Comment by nptr** [comment]
Thanks for reporting this issue. I assume in both cases (2. Test the style) and (3. Modify and test the style) it failed?

**Comment by nptr** [comment]
[Version 2.0.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.0) fixes this issue. Problem description can be found here: https://github.com/nptr/msstyleEditor/issues/67#issuecomment-1046086366
