### ISSUE TITLE
I don't know how to use the program

### ISSUE THREAD

**Issue by gilbert64** [nptr/msstyleEditor#49]
hi... uumm...
well you see, I want to make a msstyle of windows XP for startisback, but...
where's the exe to run the program?

**Comment by nptr** [comment]
Hello, on the "[Releases](https://github.com/nptr/msstyleEditor/releases)" page you can find them.
Github should make this page more prominent..

I hope you achieve what you set out to do.

**Comment by gilbert64** [comment]
thanks :D
now I have the exe
