### ISSUE TITLE
Application triggers false positive as Fuery.A!cl

### ISSUE THREAD

**Issue by eboyblue3** [nptr/msstyleEditor#5]
This application fails a heuristics check from Windows Defender and is automatically labeled as a trojan. Please look into this.

![image](https://i.imgur.com/azdHpny.png)

**Comment by nptr** [comment]
Thats probably because i compressed the executable with UPX to reduce its size. 
Unfortunately a significant amount of malware is compressed with UPX as well, which triggers some AVs heuristic...

Anyways, thanks for your report! I will consider not using UPX in the future.
