### ISSUE TITLE
Black screen after applying a theme

### ISSUE THREAD

**Issue by Yaron10** [nptr/msstyleEditor#51]
Hello,

Thank you for msstyleEditor. I'm a complete beginner in themes editing and I appreciate your work.
 
I was trying to edit a Windows Theme (**NOT located in Resources/Themes but in my Downloads folder**) with msstyleEditor and pressed "Test".
The corrupt theme was applied and I now get a black screen on reboot.

I've read https://technastic.com/recover-from-black-grey-screen-third-party-themes-on-windows-10/ but that corrupt theme is not listed under Resources/Themes.

I've used `xcopy aero "Downloads\Corrupt Theme" /i` but I do not know how to run `copy aero.theme "corrupt theme 01.theme"`.
What `.theme` file is Windows using now? And where is it located?

(Windows 10 20H2. Unfortunately I did not have a restore point).

This is an emergency. :) I'd appreciate your help.

**Comment by nptr** [comment]
Hello.

Themes applied via the "Test" feature are located in "C:\Users\Public\Documents\tmpXXXXX.msstyles". When msstyleEditor closes normally, the theme is reverted back to the one used before. This temporary file is removed afterwards. There is no theme file involved, just the visual style (.msstyles).

If you think that this temporary theme is still used by windows, you could try to replace it with a working one or maybe even delete it in the hope that windows reverts to a safe default.

**Comment by nptr** [comment]
One user reported he was able to fix it using this approach: https://github.com/nptr/msstyleEditor/issues/32#issuecomment-645983095
I don't have any more details on it however.

**Comment by Yaron10** [comment]
Hello,

I've just had access to that computer.
I've replaced the tmpXXXXX.msstyles file and all is well now.

Thank you so much. I'm truly grateful. 👍 

***

I'm a complete beginner in theme editing.
I'm even new to Win 10. I love the good old Classic Theme, and I didn't want to quit Win 7.

My system is RTL (Right To Left, Hebrew), and some potential themes on WindowsLive are not compatible.

The most important things to me are the various bars (Toolbar, MenuBar, StatusBar etc.) background color, and replacing the fonts to NON-ClearType ones. Both color and fonts **system-wide**.

What is my best option? Can I somehow import the Classic Theme from Win 7?
Would you be willing to help through the process? 
-- _If it's rather complex_, I'd pay $50 for a good and patient guide. :) 

Best regards.

**Comment by nptr** [comment]
Glad it works again. Can you remember what you did to get into this error state? msstyleEditor reverts the theme on exit, so I am a bit worried how it was still active. Did you have multiple instances running maybe?

-----

I think your best option would be finding an existing classic theme for Win10 and further modify/fix it if necessary.
@malvinas2 (a user of msstyleEditor) has one on his [Github page](https://github.com/malvinas2/ClassicThemeForWindows10), I suggest you give it a try :)

Apart from that, I can only give you some basic info as I don't have much experience on the modding part itself. I'll thus have to decline your monetary offer, but:

- For a general overview of my tool, check out the [readme](https://github.com/nptr/msstyleEditor).
- For changing window borders and a brief description of the image atlas concept, see [here](https://github.com/nptr/msstyleEditor/issues/50)
- Fonts, this is tricky (but possible) and not really implemented. See [here](https://github.com/nptr/msstyleEditor/issues/15).

It might also be worth checking out documentation or tutorials of Windows Style Builder. WSB is a structured a bit different and uses different but similar names for parts, but its definitely possible to transfer and apply the gained knowledge to msstyleEditor.
Some resources:

- https://www.vistastylebuilder.com/forum/
- https://virtualcustoms.net/forumdisplay.php/810-Windows-Style-Builder-v1-5-Tutorials

PS: If you'd like to contribute, you can always send in mini tutorials, documentation or reports bugs.

**Comment by Yaron10** [comment]
Hello Jakob,

Thank you very much for the detailed and very helpful reply. It's highly appreciated.

> Can you remember what you did to get into this error state?

I'm not absolutely sure, but I think I did the following steps:
- Downloaded [this theme](https://www.tenforums.com/attachments/customization/64575d1455644402-change-taskbar-text-font-tahoma-without-antialiasing.zip) to my `Downloads` folder.
- Opened `tahoma without antialiasing.msstyles` in msstyleEditor.
- *I'm not sure whether I edited anything or not.*
- Ran `Test` in msstyleEditor.

> msstyleEditor reverts the theme on exit

msstyleEditor did not exit gracefully. As soon as I ran `Test` I got the black screen. 

> Did you have multiple instances running maybe?

I think I had only one instance running.

***

> I think your best option would be finding an existing classic theme for Win10 and further modify/fix it if necessary.
@malvinas2 (a user of msstyleEditor) has one on his Github page, I suggest you give it a try :)

Great!
I've just briefly tested it and it looks really promising.
I'll certainly contact the developer in the coming days. :) 

> Fonts, this is tricky (but possible) and not really implemented. See here.

I actually came across https://github.com/nptr/msstyleEditor/issues/15 earlier today. 
I edited `---.msstyles.mui`, followed the rest of the steps and got the Tahoma font in the Task Bar.

Interestingly - applying only this change, Firefox has some glitches:

![תמונה](https://user-images.githubusercontent.com/10229320/118335325-10c32880-b518-11eb-8047-5c2f6c570b7e.png)

Note the caption buttons on both sides: native on the right and "weird" on the left.
It's RTL and my custom Firefox theme, but it also happens with Firefox default theme.

This also happens with https://github.com/malvinas2/ClassicThemeForWindows10.
I might have to discuss it with malvinas2.

> If you'd like to contribute, you can always send in mini tutorials, documentation or reports bugs.

At this stage it's all so new to me.
I'd certainly be glad to contribute as soon as I got a better grasp of the material.

***

Allow me to thank you again for your work and the important info.

Best regards.

**Comment by nptr** [comment]
I will consider adding a dead man's switch to the test feature, similar when changing resolution in Windows. It's not the first time a theme rendered Windows unusable...

Good luck on your undertakings! Just in case: documentation snippets and tutorials can be [put here](https://github.com/nptr/msstyleEditor/issues/52). I'll then see if and how I can integrate the information into a formal documentation.

**Comment by Yaron10** [comment]
> I will consider adding a dead man's switch to the test feature, similar when changing resolution in Windows. 

👍 
That's a great idea.

> Good luck on your undertakings!

Thanks again for your kind help.

> documentation snippets and tutorials can be put here.

I'll remember that.

***

I don't know if I should open a separate issue for the following minor improvement:
Remember msstyleEditor's window position.

Best regards.

**Comment by nptr** [comment]
Noted ;)
