### ISSUE TITLE
How to change taskbar color?

### ISSUE THREAD

**Issue by GanerCodes** [nptr/msstyleEditor#53]
I'm using a theme however translucent taskbar doesn't behave nicely with the taskbar and and I was wondering if I could somehow fix that? Here's how it looks right now:  
![image](https://user-images.githubusercontent.com/34655998/118743000-191cab80-b817-11eb-8f3d-6877cebe9f55.png)

**Comment by nptr** [comment]
I can't follow, sorry. What do you mean by _"doesn't behave nicely"_ ? 
Are you talking about this tool: [https://github.com/TranslucentTB/TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) maybe?

Until now I haven't heard of it, so best I can do are educated guesses.

**Comment by GanerCodes** [comment]
Yes, but any way to make the taskbar transparent would work

**Comment by nptr** [comment]
My only idea is to change the image at `TaskBand2 > BARBOTTOM`. It is just a template image that is then blended with the so called "Colorization Color". The colorization color is a user defined ARGB value. Its the color you can choose in the control panel.

Maybe the theme author chose a template image or changed some settings nearby that "prevent" this blending and make it seem like TBB and the windows settings have no effect? Just a guess.

Maybe there is a default colorization color inside the theme. Not sure on that one tho.

**Comment by GanerCodes** [comment]
That didn't do anything. Here's the theme im reffering to can you see if you can see how to acomplish this? https://www.deviantart.com/niivu/art/Paranoid-Android-Windows-10-Themes-821696974

**Comment by GanerCodes** [comment]
Alright I think i found it; i set images to have "None" styling under taskBan2Composited::TaskBand2

**Comment by GanerCodes** [comment]
One last thing; how do I disable the little dark-highlight behind the icons? https://i.imgur.com/D8V9tQ4.png

**Comment by nptr** [comment]
I guess that will be `TaskBand2 > TASKITEM > IMAGEFILE`. Its a 5pixel image for Win10 Aero design. Easy to miss. Each pixel represents the background color of the item for a specific state. I don't seem to have names for those states yet, but its probably "Normal", "Hot", "Pressed", "Selected" (Notification?), "Disabled" or something like that. You'll figure it out :)

![image](https://user-images.githubusercontent.com/5485569/118977982-133ddc00-b977-11eb-8439-a4b8be4e4d4e.png)

**Comment by GanerCodes** [comment]
that fixed it; however now there is a gradient highlight when I put my mouse over the icons and i cant seem to find where that is stored ![image](https://user-images.githubusercontent.com/34655998/118996872-d7425100-b94d-11eb-9898-ec5193b1ff8a.png)

**Comment by nptr** [comment]
Sorry, was busy this week. Did you figure it out? Because I don't know. But it can't be far.

**Comment by GanerCodes** [comment]
I tried but couldn't find it

**Comment by GanerCodes** [comment]
Were you able to figure it out?

**Comment by nptr** [comment]
Just tried. Its right there. At least for the "Nebula" variation. What were you doing?

![image](https://user-images.githubusercontent.com/5485569/120361857-a9281e00-c30a-11eb-9ab6-e55bad645409.png)

**Comment by GanerCodes** [comment]
I already replaced the center parts of those to make them transparent. However now there is a gradient background when I hover over the icon. How can I make the gradient solid? 
![image](https://user-images.githubusercontent.com/34655998/120373310-d01c2b00-c2dd-11eb-936c-d353339f10b9.png)

**Comment by nptr** [comment]
I thought you were talking about the blue&violet item border gradient. 

At least a part of the highlight color for opened applications seems to be derived from the application icons color.
If i set TRANSPARENT to 0, this dynamic and mouse cursor dependent highlighting is disabled. and only the static state image is shown. If you are still having a gradient background I am out of ideas.

**Comment by GanerCodes** [comment]
Thank you so much! it looks so _slick_ now. Heres the new imagefile if anyones intrested
![Taskband2-Imagefile](https://user-images.githubusercontent.com/34655998/120549784-a0daec00-c3b9-11eb-9898-306b85450ba7.png)

**Comment by nptr** [comment]
Oh nice, looks like it worked :D Enjoy!

**Comment by e-t-l** [comment]
> Alright I think i found it; i set images to have "None" styling under taskBan2Composited::TaskBand2

So that made your taskbar totally transparent?

If I wanted to make my taskbar pitch black, could I set that to \#000000?
