### ISSUE TITLE
How can I change the Explorer menu background

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [nptr/msstyleEditor#54]
please help me how i can change the color and texture of this
![image](https://user-images.githubusercontent.com/78845241/120055676-c9817f80-c061-11eb-98cf-57b25afce83f.png)

**Comment by nptr** [comment]
Of the "menu bar"? I'd have the experiment myself, but I think its the `CommandModule`.

**Comment by Yaron10** [comment]
@TheBSODAndWSODFan,

If you're referring to the Command Bar (Organize etc.) background color, you should replace the image in `CommandModule -> MODULEBACKGROUND`.

***
@nptr,

I love msstylesEditor. I'm still experimenting. :) 

Best regards.

**Comment by TheBSODAndWSODFan** [comment]
and please make msstyle editor for 32bit
because im experiment to make custom theme on windows 7 32bit vm

**Comment by nptr** [comment]
Didn't think anyone still uses 32bit Windows. But it's quickly done. Check the release section again, I added a 32-bit build:
https://github.com/nptr/msstyleEditor/releases/tag/1.5.0.0

Was `CommandModule` what you were looking for?

**Comment by TheBSODAndWSODFan** [comment]
thank you i will close the issues soon
but help me how to convert windows vista themes to windows 7?

**Comment by nptr** [comment]
You will have to identify and redo all the changes from the Vista theme in a fresh Win7 theme. There is no functionality in msstyleEditor that automates this.
