### ISSUE TITLE
Could not open the file for writing error when saving msstyle

### ISSUE THREAD

**Issue by R3n001** [nptr/msstyleEditor#55]
I'm trying to edit a msstyle, and when I try saving it, I always get the "Could not open the file for writing!" error. I have also tried the program in a VM, and it still doesn't work.

It does save a unedited copy of the file under the new name, but if I wanted that I would just use the file as is. I want to change the file.

![ScreenShot_20210630185500](https://user-images.githubusercontent.com/77039240/124041576-1d6ee380-d9d5-11eb-8fce-154986c35cea.png)

**Comment by nptr** [comment]
Hello, 

- Where are you trying to save the file to?
- This happens in other locations as well?
- Is there maybe a program accessing the file in the destination location or preventing access otherwise? (an AV maybe?)
- Is it possible that the style is in use by the OS?
- Which Windows Version did this occur on? (do I spot Win7?)

What msstyleEditor is doing: It copies the existing file to the new location and then applies all the changes to this new file.
Apparently it was able to copy the file there but could then not open it to start the edits. Since copying went fine there must
be at least partial access to the destination. Thus my questions above. Considering you even tested in a VM I assume you already ruled out those obvious issues I am hinting towards, but I gotta ask anyway.

**Comment by R3n001** [comment]
> 
> 
> Hello,
> 
>     * Where are you trying to save the file to?
> 
>     * This happens in other locations as well?
> 
>     * Is there maybe a program accessing the file in the destination location or preventing access otherwise? (an AV maybe?)
> 
>     * Is it possible that the style is in use by the OS?
> 
>     * Which Windows Version did this occur on? (do I spot Win7?)
> 
> 
> What msstyleEditor is doing: It copies the existing file to the new location and then applies all the changes to this new file.
> Apparently it was able to copy the file there but could then not open it to start the edits. Since copying went fine there must
> be at least partial access to the destination. Thus my questions above. Considering you even tested in a VM I assume you already ruled out those obvious issues I am hinting towards, but I gotta ask anyway.

I tried saving the file to desktop, but I've now tried documents and downloads, which also didn't work.

I tested the program with AV off and without an AV in a VM. both times didn't work.

I don't think a program would access the file in the destination program, especially in a VM.

The style is not in use by the OS because I can tell. It won't look like the basic theme.

I've tested it on my main 7 install, a 7 VM, and a 10 VM, all of which don't work.

**Comment by nptr** [comment]
I'll try to put a build together tomorrow that outputs more info. Maybe that helps me to track down the issue.

If possible, could you also attach the style in question? Chances are I can reproduce it locally.

**Comment by R3n001** [comment]
> 
> 
> I'll try to put a build together tomorrow that outputs more info. Maybe that helps me to track down the issue.
> 
> If possible, could you also attach the style in question? Chances are I can reproduce it locally.

https://www.deviantart.com/fediafedia/art/Windows-8-Consumer-Preview-for-Win7-289207270

**Comment by nptr** [comment]
Woahh that was fast 😁 I'll keep you updated 👍

**Comment by nptr** [comment]
On my Win7 installation the style works fine, so we'll have to further test on yours.

* Please run this build and send me a screenshot of the error message again. It should include an error code
and the destination path (you can blur your username or whatever).

* In your first post you said "_It does save a unedited copy of the file under the new name, but if I wanted that I would just use the file as is. I want to change the file._" I just saw that in case of error this file should have been deleted. If it is still there and the error persists, can you check the file permissions, ownership and try to delete it yourself?

New build (64bit):
[msstyleEditor_Test.zip](https://github.com/nptr/msstyleEditor/files/6759647/msstyleEditor_Test.zip)

**Comment by nptr** [comment]
Can't reproduce. Reopen if relevant again.

**Comment by R3n001** [comment]
> 
> 
> On my Win7 installation the style works fine, so we'll have to further test on yours.
> 
>     * Please run this build and send me a screenshot of the error message again. It should include an error code
>       and the destination path (you can blur your username or whatever).
> 
>     * In your first post you said "_It does save a unedited copy of the file under the new name, but if I wanted that I would just use the file as is. I want to change the file._" I just saw that in case of error this file should have been deleted. If it is still there and the error persists, can you check the file permissions, ownership and try to delete it yourself?
> 
> 
> New build (64bit):
> [msstyleEditor_Test.zip](https://github.com/nptr/msstyleEditor/files/6759647/msstyleEditor_Test.zip)

GitHub never notified me about this, I tried this version, and it gives this error.
![ScreenShot_20210713015004](https://user-images.githubusercontent.com/77039240/125398032-c37b0000-e37c-11eb-8628-850a9e6c5898.png)

**Comment by nptr** [comment]
According to MSDN this is:
> _ERROR_WRITE_PROTECT 19 (0x13)
> The media is write protected._

Ring any bell? Write protected media sounds weird tho given that copying went fine.
A permission problem would say ERROR_ACCESS_DENIED 5 (0x5) - thats what I would have rather expected.
Does it work when the msstyleEditor is run as Admin? And have you checked the file attributes (Rightclick the file > Properties) ? Windows likes to protect files coming from the Internet. It should look like this:

![grafik](https://user-images.githubusercontent.com/5485569/125404532-00fc7f00-e3b7-11eb-863c-02176047127a.png)

**Comment by R3n001** [comment]
So the entire reason for this was because the source file was marked as read only. 🤦
Sorry for being so retarded.

**Comment by nptr** [comment]
Don't worry, blame Microsoft for their user experience killing strategies ;)
