### ISSUE TITLE
Need help with customizing caption buttons

### ISSUE THREAD

**Issue by s1kee** [nptr/msstyleEditor#56]
Hii, im a complete noob when it comes to this and im just usually using themes that I download. I found one theme that I really liked but i want a different set of caption buttons so i tried to replace the resource images but when i tried to apply it it didnt change?? These are the ones to replace right? Or did i miss a complete section? :(( 

![image](https://user-images.githubusercontent.com/89289139/131870238-a08f36b2-8e14-4391-9bec-5de1f9cf0be3.png)

**Comment by s1kee** [comment]
nvm i figured it all out by reading the wiki, shouldve read it first before posting this my bad :/

**Comment by nptr** [comment]
Good to hear, no worries! If you feel information is missing or needs further clarification, let me know. I then can improve upon the wiki.
