### ISSUE TITLE
Tree View catagories for classes

### ISSUE THREAD

**Issue by wealstarr** [nptr/msstyleEditor#58]
Hello,

It would be far (far) more easier to work with if the classes are organised in their own respective categorizes and can viewd as the three view. Please consider adding this option. 
![image_2021-09-12_125248](https://user-images.githubusercontent.com/26643729/132977591-761c732d-dc8b-4ff1-acba-a608cc7cf318.png)

**Comment by nptr** [comment]
I heard both sides. Some are preferring a plain list, some a hierarchy and categorization. Personally I tend more towards the list.

Are you thinking of categorization by usage as WSB does, or would grouping related classes work as well?

**Comment by wealstarr** [comment]
Hello nptr,

Thank you for the response and consideration of my request. I think WSB does the best. With hierarchy and categorization everything is well organized and easier to work with. If there are different opinions about this, program could have an option to view in different settings.

Regards
Wealstarr.

**Comment by wealstarr** [comment]
You don't have to "clone" the WSB classmaps but you can use them as a reference. No objection in doing so. For example: How many things are common in different browsers or anti-virus softwares ? When one implement a new feature, others use that as a reference and rush to copy/introduce the same feature. No one complaints about that. Point being while it's not okay to "clone" the WSB classmaps, it's totally okay in my opinion to use them as a reference point.
