### ISSUE TITLE
Tabbed MINDPI image view

### ISSUE THREAD

**Issue by wealstarr** [nptr/msstyleEditor#59]
Images for MINDPI resolutions open as tree view, it's more efficient in my opinion to be able to view them in the tabs instead. Please consider adding this option.
![image_2021-09-12_125635](https://user-images.githubusercontent.com/26643729/132977707-d73015b2-60b9-4632-a737-7da2ae48dcc7.png)

Thanks you.

**Comment by nptr** [comment]
[Version 2.0.0.0](https://github.com/nptr/msstyleEditor/releases) does something like this now.
