### ISSUE TITLE
[Request] Adding New Property Feature

### ISSUE THREAD

**Issue by JustReadThis** [nptr/msstyleEditor#6]
Hi. 
I using your app recently and found a suggestion.
Maybe you could add new property feauture.
I think that's make a huge impact on your app, because can read and edit data/property is good enough.
New Property value like SIZINGMARGINS, CONTENTMARGINS, etc.
Maybe you could limit new property that can be added.
Sorry for sudden suggest. I think this app will become great tool for editing style theme.

**Comment by nptr** [comment]
Yes, adding/removing properties has been on my "to-do" list quite some time now, so i will not forget your suggestion. However, i can't say when i'll implement it.

**Comment by nptr** [comment]
[V1.3.0.0-beta](https://github.com/nptr/msstyleEditor/releases/tag/1.3.0.0-beta) features adding/removal of properties. It's still a beta version, but a full release will eventually come. I'm closing this request now, anyhow, feel free to open issues regarding feedback and problems with the beta :)
