### ISSUE TITLE
Key name of the little bar under taskbar icons?

### ISSUE THREAD

**Issue by GanerCodes** [nptr/msstyleEditor#62]
![image](https://user-images.githubusercontent.com/34655998/136857317-11e0f95c-f6a7-46a4-942e-19b44e8f7d15.png)
Also, is this the tool to change the spacing between taskbar icons?

**Comment by nodgear** [comment]
@GanerCodes Have you done it?

**Comment by GanerCodes** [comment]
> @GanerCodes Have you done it?

I switched to Linux now lol

**Comment by nodgear** [comment]
> > @GanerCodes Have you done it?
> 
> I switched to Linux now lol

That's a smart move, i guess i won't bother checking diff then.
best of luck!

**Comment by GanerCodes** [comment]
> That's a smart move, i guess i won't bother checking diff then. best of luck!

Thanks! I'm having a much better experence on it than Windows, highly recommended it to anyone who's tinkering with Windows at this level of detail lol

**Comment by nptr** [comment]
Yep, the time spent tinkering with the messy Windows UI is much better spent learning a new skill and gaining some independence.
Linux experience looks much better on your résumé too.
