### ISSUE TITLE
off-topic: Context menu ID?

### ISSUE THREAD

**Issue by rocco-xyz** [nptr/msstyleEditor#68]
Kinda off-topic but ...
Do you have any idea how can I change the color of the context menu of the light theme of Windows 10?
The color changed since version 1903, I prefer the old color of version 1809 because it was easier to see ...

![1809-1903_context_menu_colors](https://user-images.githubusercontent.com/16656467/144516750-64771d6b-cfe5-46ab-b183-031215febbb5.jpg)
Note: The color in the image may vary because of the compression of the JPG format, but the color codes are correct.

I used msstyleEditor to edit the file "aero.msstyles" (located in C:\Windows\Resources\Themes\Aero\) and searched for the color 217, 217, 217 but it did not find any element with that color.
But I know however that replacing the "Resources" folder (located in C:\Windows) from a Windows v1809 installation  to a v1903 does revert the color, however, doing so causes some glitches in the contex menus of the taskbar and taskbar items.

> [can't edit certain property types](https://github.com/nptr/msstyleEditor#limitations)

Are the context menus some of the properties that msstyleEditor can't read/edit?

**Comment by nptr** [comment]
I think it is an image. Try exporting, editing and replacing the image in `Menu > POPUPITEM`. This allows for more complex, non-flat selection markers like you had in Windows 7. The images are typically very small and are upscaled with 9-slice scaling. This also is where the SIZINGMARGINS and CONTENTMARGINS properties come into play. That is not relevant for you in this case however.

**Comment by rocco-xyz** [comment]
Hello my friend.
It seems that, unfortunately all the resources and properties of the POPUPSUBMENU list tree...

IMAGEFILE1	
IMAGEFILE2	
IMAGEFILE3	
IMAGEFILE4	
IMAGEFILE5	
IMAGEFILE6	
IMAGEFILE7	
  SYSTEMCLOSE	
IMAGEFILE1	
IMAGEFILE2	
IMAGEFILE3	
IMAGEFILE4	
IMAGEFILE5	
IMAGEFILE6	
IMAGEFILE7	
  SYSTEMMAXIMIZE	
IMAGEFILE1	
IMAGEFILE2	
IMAGEFILE3	
IMAGEFILE4	
IMAGEFILE5	
IMAGEFILE6	
IMAGEFILE7	
  SYSTEMMINIMIZE	
IMAGEFILE1	
IMAGEFILE2	
IMAGEFILE3	
IMAGEFILE4	
IMAGEFILE5	
IMAGEFILE6	
IMAGEFILE7	
   SYSTEMRESTORE	
IMAGEFILE1	
IMAGEFILE2	
IMAGEFILE3	
IMAGEFILE4	
IMAGEFILE5	
IMAGEFILE6	
IMAGEFILE7

...are identical in the "aero.msstyles" file of versions 1809 and 1903 of Windows...
I think it will be more difficult than I initially thought; Anyway, I will continue to investigate this matter and if I find something, I will return to report it.
Thanks for your answer.

**Comment by nptr** [comment]
A few suggestions:

- You can do "File > Export > Style Info" for both, and then compare the two files with a diff tool. It will give you an overview of all the differing properties and might narrow down your search.

- Export some of promising images, paint the individual components different colors. Then replace the image and apply the theme. You will immediately see their effect.


`Menu > POPUPITEM` works on my Windows 7 for example. Image:
![popitem](https://user-images.githubusercontent.com/5485569/144717624-6d3349f8-7be2-4d78-97bf-ec5e30a72921.png)

Its effect (ignore the turquoise explorer background):
![grafik](https://user-images.githubusercontent.com/5485569/144717787-8054bb81-23b6-447b-b90b-9ac8a7c09f5e.png)
