### ISSUE TITLE
on Windows 10 RS4 aero.msstyle not work after msstyleEditor

### ISSUE THREAD

**Issue by geepnozeex** [nptr/msstyleEditor#7]

**Comment by nptr** [comment]
Sorry for the inconvenience! Hopefully the next version does better.
Unfortunately, without more information im not able to provide further help.

- Is your uxtheme patched?
- What exactly are you experiencing?
- What properties did you change?
- Could you track the problem to a specific property?
- What was it's value before, to what did you change it?

**Comment by geepnozeex** [comment]
1 - ofcourse  - UltraUXThemePatcher_3.3.4
2 - modified style does not apply
3 - only one color - ProperTree
win 10 ver.1803 RS4

**Comment by nptr** [comment]
Thanks for the report! I'm in the process of rewriting and improving the whole read & write logic 
anyways and will keep this issue in mind.

**Comment by nptr** [comment]
Issue might be fixed in [V1.3.0.0-beta](https://github.com/nptr/msstyleEditor/releases/tag/1.3.0.0-beta).
And as always, feedback is greatly appreciated!
