### ISSUE TITLE
New Icon design by me （Fluent Design）

### ISSUE THREAD

**Issue by Shomnipotence** [nptr/msstyleEditor#72]
![image](https://user-images.githubusercontent.com/6630660/154797674-5aee43ef-887e-4a78-991f-befef419c586.png)
You can tell me what you want. I will do it as what I can do as possible.
![image](https://user-images.githubusercontent.com/6630660/154847339-57de746a-305e-4161-8e3e-4fd064202b3b.png)
![image](https://user-images.githubusercontent.com/6630660/154878292-ddc3cc2d-f10b-49c9-894c-c72dc335abeb.png)

**Comment by nptr** [comment]
That looks quite nice! msstyleEditor 2.0.0.0 is currently in the works and could indeed use better icons if you really want to give it a go. For the application icon I'd prefer to keep a hammer in front of the window - as trademark so to say. The window and hammer can be styled as seen fit though.

App icon should be: 16x16, 24x24, 32x32, 48x48, 64x64 and 256x256 i guess. All 32bit .png or one ready made .ico
(https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos#target-size-app-icon-assets)

I'll add a screenshot of the upcoming version so you can harmonize the colors with the current icon set.

**Comment by Shomnipotence** [comment]
> That looks quite nice! msstyleEditor 2.0.0.0 is currently in the works and could indeed use better icons if you really want to give it a go. For the application icon I'd prefer to keep a hammer in front of the window - as trademark so to say. The window and hammer can be styled as seen fit though.
> 
> App icon should be: 16x16, 24x24, 32x32, 48x48, 64x64 and 256x256 i guess. All 32bit .png or one ready made .ico (https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos#target-size-app-icon-assets)
> 
> I'll add a screenshot of the upcoming version so you can harmonize the colors with the current icon set.

Yeah that is what I need，your Accent Color（Brand Color） of this app，and I will give you the ico file which is a set of 16-256 img in one file.

**Comment by nptr** [comment]
Here is what it currently looks like. The Icon set is still a bit thrown together. It's a mix of the Visual Studio 2019 and 2022 Image Library.
![image](https://user-images.githubusercontent.com/5485569/154838187-3deb470d-85b2-4e8a-bce7-096ef78415e0.png)

Yes, I really like the resource hacker icons! Especially the first one:
![image](https://user-images.githubusercontent.com/5485569/154838667-23cd52d0-3d6c-46be-94c2-2343888dc60c.png)
I could image that in approximately the colors of my current icon (i think they work good on dark an light backgrounds) and with a hammer or other tool on top. But I think you know better what to do :D
![image](https://user-images.githubusercontent.com/5485569/154838702-24ba62c8-b9d9-4767-9d2c-8d6ab6cc13a6.png)

**Comment by Shomnipotence** [comment]
> 这是它目前的样子。图标集仍然有点混乱。它是 Visual Studio 2019 和 2022 图像库的混合体。 ![图片](https://user-images.githubusercontent.com/5485569/154838187-3deb470d-85b2-4e8a-bce7-096ef78415e0.png)
> 
> 是的，我真的很喜欢资源黑客图标！尤其是第一个： 我可以用我当前图标的颜色（我认为它们在深色和浅色背景上效果很好）和顶部的锤子或其他工具来想象它。但我认为你更清楚该怎么做：D ![图片](https://user-images.githubusercontent.com/5485569/154838667-23cd52d0-3d6c-46be-94c2-2343888dc60c.png) ![图片](https://user-images.githubusercontent.com/5485569/154838702-24ba62c8-b9d9-4767-9d2c-8d6ab6cc13a6.png)



> Here is what it currently looks like. The Icon set is still a bit thrown together. It's a mix of the Visual Studio 2019 and 2022 Image Library. ![image](https://user-images.githubusercontent.com/5485569/154838187-3deb470d-85b2-4e8a-bce7-096ef78415e0.png)
> 
> Yes, I really like the resource hacker icons! Especially the first one: ![image](https://user-images.githubusercontent.com/5485569/154838667-23cd52d0-3d6c-46be-94c2-2343888dc60c.png) I could image that in approximately the colors of my current icon (i think they work good on dark an light backgrounds) and with a hammer or other tool on top. But I think you know better what to do :D ![image](https://user-images.githubusercontent.com/5485569/154838702-24ba62c8-b9d9-4767-9d2c-8d6ab6cc13a6.png)

Amazing Work！

However I prefer Command Bar than Ribbon. it matches Fluent Design System more than the Ribbon.
Another reason is that, Windows Vista(-Windows 7) has command bar,too. It is called Tool Bar.
![image](https://user-images.githubusercontent.com/6630660/154839743-a20a1560-109a-4a2e-934a-f6999879a600.png)
![image](https://user-images.githubusercontent.com/6630660/154839812-c4f5cd87-0ec9-4642-87c1-591bff6792c7.png)

Well, but we should go head.The above discussion about Ribbon and the command bar is just my personal advice

Let's talk about The App Icon.

I would probably prefer to use more saturated, more vibrant colors. 
E.g
![image](https://user-images.githubusercontent.com/6630660/154840026-d1211559-36fe-4007-a606-4bc8baba617b.png)
https://github.com/veler/DevToys

I will give about three to four versions

Purple background, white/light grey/grey or brown hammer

Lilac background, purple hammer shape

Lilac background, hammered in white/light grey/grey or brown (closer to the current colour scheme)

Off-white background/dark gray background, purple hammer

**Comment by Shomnipotence** [comment]
> Here is what it currently looks like. The Icon set is still a bit thrown together. It's a mix of the Visual Studio 2019 and 2022 Image Library. ![image](https://user-images.githubusercontent.com/5485569/154838187-3deb470d-85b2-4e8a-bce7-096ef78415e0.png)
> 
> Yes, I really like the resource hacker icons! Especially the first one: ![image](https://user-images.githubusercontent.com/5485569/154838667-23cd52d0-3d6c-46be-94c2-2343888dc60c.png) I could image that in approximately the colors of my current icon (i think they work good on dark an light backgrounds) and with a hammer or other tool on top. But I think you know better what to do :D ![image](https://user-images.githubusercontent.com/5485569/154838702-24ba62c8-b9d9-4767-9d2c-8d6ab6cc13a6.png)

Regarding Ribbon area icons, my suggestion is to use the mono/color bi-color (stroke + translucent fill) version of Segoe Symbol whenever possible.

Since there is no better way to be compatible with the visual styles of different platforms at the same time, unless you prepare three sets of icons for different versions of the system (Windows 11/10/ 8 use Segoe; Windows 7/Vista use one, Windows XP uses one) 's suggestion is to keep as close as possible to the latest version. More importantly, 8/10/11 are all compatible with the same visual style, only slightly different in details.

**Comment by nptr** [comment]
I'm looking forward to your contribution!

The ribbon and it's icons I'll keep for now. Got to finish functionality first ;)

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154841863-99d896d7-10ff-4365-acf8-2c78e6c2ae04.png)
Just a test

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
It is good, but I doubt that it is able to scale to small sizes whilst retaining visual clarity, because the logo is complex. This problem is less present for the previous version, and is why the logogram of Resource Hacker is as basic as it is.

**Comment by Shomnipotence** [comment]
> I am doubtful that those logograms are able to scale to small sizes whilst retaining visual clarity, because they are complex. This problem is less present for the previous logo, and is why the logo of Resource Hacker is as basic as it is. Despite that, the pleasantness of the appearance of the proposed logos are significant superior to the current one.

![image](https://user-images.githubusercontent.com/6630660/154845874-bd8332a5-693b-4fbe-a43b-cebae7e359ce.png)

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154846177-35a51540-86b2-4cfa-82a5-d880f485fe8a.png)

**Comment by nptr** [comment]
I am not a fan of the subtle outlines that show the window. I'd use the first or third one from your resource hacker image, but in violett/blue and some contrasting color. I think it more clearly shows the windows. The hammers are great, I'd use whatever matches the window.

Like this maybe? Although the light blue part on the left vanishes for light backgrounds :(
![image](https://user-images.githubusercontent.com/5485569/154846626-94655a32-824f-49f8-bcdc-14ee4c27d019.png)

16x16 and 32x32 will be the hardest. but most important probably. You likely have to draw them manually or use a different image: https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#level-of-detail

Don't get me wrong, I like your images way better than mine :) It's about finding the perfect fit :D

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> > I am doubtful that those logograms are able to scale to small sizes whilst retaining visual clarity, because they are complex. This problem is less present for the previous logo, and is why the logo of Resource Hacker is as basic as it is. Despite that, the pleasantness of the appearance of the proposed logos are significant superior to the current one.
> 
> ![image](https://user-images.githubusercontent.com/6630660/154845874-bd8332a5-693b-4fbe-a43b-cebae7e359ce.png)

Is the size of that 24-by-24 or 36-by-36? I was referring to 16-by-16.

**Comment by Shomnipotence** [comment]
> > > I am doubtful that those logograms are able to scale to small sizes whilst retaining visual clarity, because they are complex. This problem is less present for the previous logo, and is why the logo of Resource Hacker is as basic as it is. Despite that, the pleasantness of the appearance of the proposed logos are significant superior to the current one.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/6630660/154845874-bd8332a5-693b-4fbe-a43b-cebae7e359ce.png)
> 
> Is the size of that 24-by-24 or 36-by-36? I was referring to approximately 16-by-16, because that is the most small size that is commonly utilised.

![image](https://user-images.githubusercontent.com/6630660/154848375-e91046da-fcc2-4f41-8a61-4d9785397c99.png)

Normaly，Task Bar use 64x64px

**Comment by Shomnipotence** [comment]
> I am not a fan of the subtle outlines that show the window. I'd use the first or third one from your resource hacker image, but in violett/blue and some contrasting color. I think it more clearly shows the windows. The hammers are great, I'd use whatever matches the window.
> 
> Like this maybe, with hammer and better harmonized colors? ![image](https://user-images.githubusercontent.com/5485569/154847645-680c1da4-0b08-44f9-90a5-c02859e68848.png)
> 
> 16x16 and 32x32 will be the hardest. but most important probably. You likely have to draw them manually or use a different image: https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#level-of-detail
> 
> Don't get me wrong, I like your images way better than mine! It's about finding the perfect fit :) Take your time, there is no release pressure :)

One of my 

> I am not a fan of the subtle outlines that show the window. I'd use the first or third one from your resource hacker image, but in violett/blue and some contrasting color. I think it more clearly shows the windows. The hammers are great, I'd use whatever matches the window.
> 
> Like this maybe, with hammer and better harmonized colors? ![image](https://user-images.githubusercontent.com/5485569/154847645-680c1da4-0b08-44f9-90a5-c02859e68848.png)
> 
> 16x16 and 32x32 will be the hardest. but most important probably. You likely have to draw them manually or use a different image: https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons#level-of-detail
> 
> Don't get me wrong, I like your images way better than mine! It's about finding the perfect fit :) Take your time, there is no release pressure :)

One of the reasons I chose to use outlines instead of color blocks is that it better hints at the function and purpose of the product - customizing the look - buttons, borders, layout... and color blocks alone don't satisfy that.

WindowsTerminal's icon alludes to its tabs and below, its iconic >:\

The left-right split of my ResourceHacker icon hints at its iconic treemap-details list.

I'll give it a try though, but I sincerely recommend against using the cross-split as it's not sufficiently suggestive of functionality.

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154850074-aef156c8-e678-43bf-aaf1-4a8f4fc18c14.png)

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154851146-2fc5ad7e-5e60-408a-a84a-ce1069cf2011.png)

**Comment by nptr** [comment]
I like Frame 7 best! The title bar is nicely visible and it is immediately clear that the rectangle is a window. The colors are close to the the previous icon, so there is some continuity. That is the way to go. Maybe a bit more contrast between titlebar and window.

Thanks for all those suggestions. I'm curious how it will look like :)

**Comment by Shomnipotence** [comment]
> I like Frame 7 best! The title bar is nicely visible and it is immediately clear that the rectangle is a window. The colors are close to the the previous icon, so there is some continuity. That is the way to go. Maybe a bit more contrast between titlebar and window.
> 
> Thanks for all those suggestions. I'm curious how it will look in action :)

Although you think 7 is your favorite solution, as a designer, I think a solution like 7 is closer to a general reverse engineering tool (eg Resource Hacker) than to UI modification. The window edge is a generic symbol that represents UI construction.
I think 2，10，9，1，and 12 can better reflect the function of this software.

**Comment by nptr** [comment]
I believe users don't interpret that much into icons i think ;) But I trust you and am open if you want to give e.g. Frame 9 or Frame 12 a try.

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154940313-06b833d3-fea7-4866-8b2e-27dbb19208c2.png)

**Comment by nptr** [comment]
You can zip and attach them here. I'll make a build with them asap and see how it performs.

**Comment by nptr** [comment]
What do you think?

![Taskbar](https://user-images.githubusercontent.com/5485569/154972578-de4f65cd-3923-4970-8be4-c4c0fcb615c9.PNG)

![TaskbarCloseuup](https://user-images.githubusercontent.com/5485569/154973700-01ea71aa-6853-49dd-8ac9-202b41a68693.PNG)

![TitleBarIcons](https://user-images.githubusercontent.com/5485569/154973757-b78e532f-a34f-431f-8f24-f56c49f57142.PNG)

![TitleBarIconsCloseup](https://user-images.githubusercontent.com/5485569/154972866-8e8ed7b8-ca1e-4859-8d4e-93241e397833.PNG)

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154975883-ebd2e71a-589b-4444-b36f-bf1bcd1b423f.png)
![image](https://user-images.githubusercontent.com/6630660/154976011-e9bd12e2-533b-40d7-83f1-0ba3698a0fca.png)
We need a bigger one

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154978283-f498db3c-bce5-49e1-8e8f-60d52e766e06.png)
![image](https://user-images.githubusercontent.com/6630660/154978430-6788484d-0e3a-4384-836f-000648a65e24.png)
![image](https://user-images.githubusercontent.com/6630660/154978600-1b2c668b-219f-41da-a012-832a710d240e.png)

**Comment by nptr** [comment]
I think:
- stronger contrast
- bigger window (nearly fill the available space) => done
- native resolution images for 16x16, 32x32 and 48x48. The bi-linear scaling hurts. Nearest neighbor also isn't ideal as it introduces aliasing.

**Comment by Shomnipotence** [comment]
> I think:
> 
> * stronger contrast for the window frame lines
> * bigger window (nearly fill the available space) => done
> * native resolution images for 16x16, 32x32 and 48x48. The bi-linear scaling hurts. Nearest neighbor also isn't ideal as it introduces aliasing.

I will do it , after I edit the Hummer shape

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154981887-dae99923-55a8-43bc-becf-1c66e130747c.png)
bigger hammer

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154986106-a0a13296-3e4f-427a-8032-491e9d8ff21b.png)
![image](https://user-images.githubusercontent.com/6630660/154986144-0f6a94bb-607f-482a-b2ab-e675c4b81227.png)

I think it works now @nptr .

**Comment by nptr** [comment]
I agree, size is better now!

**Comment by Shomnipotence** [comment]
[Frame 19.zip](https://github.com/nptr/msstyleEditor/files/8113224/Frame.19.zip)
![Frame 19](https://user-images.githubusercontent.com/6630660/155052512-d3e2f9ca-39e7-482b-b891-b8d5dc6a3ff4.png)

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/155095880-7d265915-1025-4591-ae7d-31f2d1103279.png)

**Comment by nptr** [comment]
Still a fan of frame of 17 btw ;)

![TitleBar](https://user-images.githubusercontent.com/5485569/155220130-43419965-1231-46a5-baa2-83157ec07504.PNG)
![TitleBarBig](https://user-images.githubusercontent.com/5485569/155220447-2dbd059b-5a76-4185-bc6d-fbd54d8a2de5.PNG)


![TaskBar](https://user-images.githubusercontent.com/5485569/155220255-8005f026-b3de-4ca6-af11-2d9d435814bb.PNG)
![TaskBarBig](https://user-images.githubusercontent.com/5485569/155220264-e8c5bef3-3817-41cf-a51a-c71c056fb7ed.PNG)

**Comment by Shomnipotence** [comment]
> 

Thay are svg infact.


You can import svg 
https://www.figma.com/file/1QDfozGaRUB0A0xUKu3Nd1/msstyleEditor?node-id=5%3A2

**Comment by Shomnipotence** [comment]
> Still a fan of frame of 17 btw ;) Size is perfect. Native res. images would be next. Although I can probably make a vector graphic based on your images and unburden you?
> 
> ![TitleBar](https://user-images.githubusercontent.com/5485569/155220130-43419965-1231-46a5-baa2-83157ec07504.PNG) ![TitleBarBig](https://user-images.githubusercontent.com/5485569/155220447-2dbd059b-5a76-4185-bc6d-fbd54d8a2de5.PNG)
> 
> ![TaskBar](https://user-images.githubusercontent.com/5485569/155220255-8005f026-b3de-4ca6-af11-2d9d435814bb.PNG) ![TaskBarBig](https://user-images.githubusercontent.com/5485569/155220264-e8c5bef3-3817-41cf-a51a-c71c056fb7ed.PNG)

Thay are svg infact.

You can import svg
https://www.figma.com/file/1QDfozGaRUB0A0xUKu3Nd1/msstyleEditor?node-id=5%3A2

**Comment by Shomnipotence** [comment]
> Nice! I'll have a look at it

but you have not done it until now

**Comment by nptr** [comment]
No I did. I exported Frame 17 SVG yesterday and play around with it offline. I noticed that InkScape doesn't render like browsers do, now I am working with the online tool you are using.

Currently I am working on the drop shadows, because they are a bit weird:
![grafik](https://user-images.githubusercontent.com/5485569/155513563-99d9c48d-fb5e-4ce5-bc17-b4a4c942729e.png)

**Comment by Shomnipotence** [comment]
> No I did. I exported Frame 17 SVG yesterday and play around with it offline. I noticed that InkScape doesn't render like browsers do, now I am working with the online tool you are using. And I am rather busy. Hobby has to wait a bit sometimes. Give me some time ;)
> 
> Currently I am working on the drop shadows, because they are a bit weird: ![grafik](https://user-images.githubusercontent.com/5485569/155513563-99d9c48d-fb5e-4ce5-bc17-b4a4c942729e.png)

Ah my problem,

![image](https://user-images.githubusercontent.com/6630660/155514554-ea191da8-0e83-4a30-aed4-8e6b3e9163dc.png)

Now it is clear and...(Look at the task manager icon, its border has no shadow,too)

but it still has a problem, but my suggestion is....relaxing....

**Comment by nptr** [comment]
Here is what I got: [ico.zip](https://github.com/nptr/msstyleEditor/files/8132805/ico.zip) I'll probably settle for this.
Did some color/contrast tweaks, aforementioned shadows, minor fixes on the exported pngs etc. Credits are of course still yours.

Now I just have to release the next version :) Thanks for your contribution, I appreciate it!

**Comment by Shomnipotence** [comment]
> Here is what I got: [ico.zip](https://github.com/nptr/msstyleEditor/files/8132805/ico.zip) I'll probably settle for this. Did some color/contrast tweaks, aforementioned shadows and minor fixes on the exported .png. Credits are of course still yours.
> 
> Now I just have to release the next version :) Thanks for your contribution, I appreciate it! Let me know how to reference you. Name, Website etc.

Amazing, but my last suggestion is that dont close the shadow of the hummer, even through it overflow the purpose window.

**Comment by nptr** [comment]
Yes, I kept the shadow. I only removed the overflowing portion in post-processing.

**Comment by Shomnipotence** [comment]
> Yes, I kept the shadow. I only removed the overflowing portion in post-processing. Didn't feel like tinkering with SVG.

yeah but I find that in ico file，you deleted the shadow of the hammer

**Comment by nptr** [comment]
There is one, maybe a bit weak. Anyways, I'll leave it for now and maybe revisit this topic later.
You can checkout the icon in the [alpha release](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.0-alpha), and maybe replace it with your personal favorite :)

**Comment by nptr** [comment]
Version 2.0.0.0 is out of beta and features the new icon. I consider this issue closed now :)
