### ISSUE TITLE
How to msstyles - path and instructions

### ISSUE THREAD

**Issue by marmmc** [nptr/msstyleEditor#76]
hello, can you tell me 3 things in msstyles app????

1) where, exact location does the windows start button change?
2) where, exact location change the buttons minimize, close, etc..?
3) where, exact location I change the background images, like leaving the style DARK, or WHITE;

first time use?
thanks.

**Comment by nptr** [comment]
1.) The "Start" button is not actually part of the msstyles file. Its a resource in explorer.exe itself. Use Resource Hacker or similar for this.
2.) For the Min/Max/Close button, see the Wiki: https://github.com/nptr/msstyleEditor/wiki/Window-Frames
3.) The backgrounds are complicated. You'd have to change the background color/image for all possible controls. This will require some learning and experimentation on your part.

**Comment by marmmc** [comment]
tankyou my brother!!!
i am working and practice...

**Comment by marmmc** [comment]
Does anyone have a theme in black, dark to contribute, that is very light, like the lite of WINDOWS 10, but only black, really lite??? if yes, they contribute... that doesn't use a lot of memory and graphics...
