### ISSUE TITLE
Main theme open, import other theme variables.

### ISSUE THREAD

**Issue by Rootkit-** [nptr/msstyleEditor#78]
Ideally I got a skin that is missing critical I think states?
Theme i like
![image](https://user-images.githubusercontent.com/5389279/160257982-1825ae32-bb65-4c13-9c3f-29ac8a23139c.png)
theme that has it all looking right
![image](https://user-images.githubusercontent.com/5389279/160258000-a558c56f-b734-4cd2-a954-8c098cbb0a93.png)

**Comment by nptr** [comment]
No, its an image property you want.
Compare the entries in the property view. You will find that the second one likely has those properties:

- BGTYPE=IMAGEFILE 
- IMAGEFILE=<resource id>
