### ISSUE TITLE
Question from a Noob

### ISSUE THREAD

**Issue by gaveitatry** [nptr/msstyleEditor#8]
Hi.  I had a four year old Acer laptop with Windows 8.1 that I accidentally broke on April 11, 2018.  I had to order a new laptop on Amazon, which arrived on April 18, 2018.  I am in the process of setting my laptop now, and it is taking some time.  For one, Windows 10 is a bit different from Windows 8.1.  I did not like the disappearing borders.  Then I tried someones "aero 8" msstyle with the UltraUxThemePatcher, and it gave me borders that didn't disappear, but there were severe issues with window sizes and positions.  After yet another week, I finally gave the "aerolite" msstyle a try and found out that it fixed any and all window size and position problems that I was having.  It's perfect.  So I am going to use "aerolite" msstyle from now on.

One thing though.  My accent color is white, so I see white title bars and white window borders, which is what I want.  But on the very outside of those accent borders, is a different gray border.  This gray border is pretty dark gray when the window is active, and it becomes a lighter gray when the window becomes inactive.  I am just going to give approximations.  The inactive border is around #555555 and the active border is around #353535.  The #353535 is definitely too dark.  I might be happy if both the inactive and active borders were #555555, but chances are I might want them even slightly lighter than that.

The thing is, I have no idea where to start.  What do I do?  I had uninstalled UltraUxThemePatcher when I switched to the "aerolite" msstyle because I no longer needed it.  But when I opened up "aerolite" mssstyle in msstyleEditor and then saved it without making any changes and then edited my theme to use the NEW msstyle that I just created, it made my computer look like a regular "aero" msstyle theme with only 1px borders and white accent colors.  So I am thinking that I need to install UltraUxThemePatcher to see any new "aerolite" msstyle that I create?

Actually let me just ask my questions.  If I want to have everything identical to the original "aerolite" msstyle and only change the very outer borders (not the accent borders), how do I go about doing that?  What thing inside msstyle do I need to change and do I have to have anything installed?  Also, will loading the original "aerolite" msstyle in msstyleEditor load all the "aerolite" settings without changing them to "aero"?  Oh, and I guess one more question.  Does the active and inactive borders (not the accent color borders) have to be of the same color, like gray, or can they be completely different colors like pink vs blue?

Thanks in advance.

**Comment by nptr** [comment]
Yes, every file saved by the msstyleEditor requires a patched theme engine. The slightest change
will invalidate the themes signature and windows will reject it. Even **saving** without modifications will alter the file (internal stuff). So you'll need the UltraUxThemePatcher or similar.

About what to do:
I usually backup the style i want to replace (at least the .msstyles file), and then just replace the original .msstyles file with the edited one. Maybe even create a restore-point in case things go bad.

Regarding the borders, I actually don't know. I don't even have a windows 10 machine, so i can't test, but i can take a guess based on a random W10 visual style i've lying around.

Look at **DWMWindow > CommonProperties**. There is a texture atlas that defines the visual appearance of the window. In **DWMWindow > FRAME[XX] > Common** you will find **ATLASRECT** properties that define the area of that part of the window inside the atlas. When i export it and look at it in an image editor, i see an alpha-only gradient. So i guess the OS mixes that with the accent color. The gradient (when scaled) probably produces that darker outer border. You could remove that gradient, or color it and see what happens.

Also look at the states in **DWMWindow > FRAMETOP**. Maybe the **OPACITY**, **COLORIZATIONCOLOR** and **COLORIZATIONOPACITY** properties in some of the states come into play when the window is unfocused etc.


About having different color per state:
In theory i guess that can work. Maybe have different gradients in the atlas, and an **ATLASTRECT** property in each state that selects the correct pre-colored gradient. Unfortunately, adding/removing properties is work-in-progress and not released yet.


Good luck!

**Comment by gaveitatry** [comment]
Thank you for the speedy and detailed response.  I will give it a try soon.  Even if it ends up not working, you still gave me a peace of mind and information that I didn't previous have.  Thank you and have a great day, year, etc.
