### ISSUE TITLE
Unable to replace and export secondary images to a class.

### ISSUE THREAD

**Issue by OrthodoxWindows** [nptr/msstyleEditor#80]
*Windows Version*: <<Windows 10 21H2>>

**Expected behavior**
In the latest version, it is not possible to change and export secondary images. For example, the change and export of _IMAGEFILE_ takes place without problem, but the replacement of _IMAGEFILE1, IMAGEFILE2... is not possible. 
Maybe it is possible, but in this case, it means that something escapes me.

**Checklist**
- [X] My uxtheme.dll is patched
- [X] I am using the latest version of msstyleEditor
- [X] None of the other issues cover this

**Comment by nptr** [comment]
I'll look into it. Since I reworked that part recently, its likely there is a bug.

**Comment by nptr** [comment]
Fixed it and released [V 2.0.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.0.0.0) in the process. I hope its relatively bug free :)

**Comment by OrthodoxWindows** [comment]
Thank you for for the fix !
