### ISSUE TITLE
Make settings persistent across application starts

### ISSUE THREAD

**Issue by adacom81** [nptr/msstyleEditor#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
the view button brings up 4 choices for the background in image background - the default is chequered which imo is the wrong one but thats just my opinion - i set it to grey which seems a better choice but the change does not stick on the next session - is this intentional or a bug - is it possible to make it a stuck setting

**Describe alternatives you've considered**

**Additional context**
Everything you think helps the feature request materialize.
* screenshots and sketches
* contributions you can provide

**Comment by nptr** [comment]
I like to have the application portable and not unload too much stuff on my users disk. Should there ever be a real need I can be convinced to manage an application directory, settings and maybe an installer, but so far I feel its not necessary.
