### ISSUE TITLE
How to run the app

### ISSUE THREAD

**Issue by PatternFinder** [nptr/msstyleEditor#85]
*Windows Version*: Win 10

**Question**
How to run the app without any knowledge of how C# apps work. Is there a way to convert the sln to exe file?

Thanks for answer a simple question.

**Comment by nptr** [comment]
Github is developer centric and displays the source code more prominently than the release (download) section.
You can find the precompiled binary here: https://github.com/nptr/msstyleEditor/releases

The same page is also reachable from the applications main page via the sidebar on the right.
