### ISSUE TITLE
Unable to test visual style whether high contrast mode is enabled

### ISSUE THREAD

**Issue by OrthodoxWindows** [nptr/msstyleEditor#89]
**Windows Version** : Win 10 21H2

**Expected behavior**
When the high contrast mode is activated, I get this error (in the screenshot) when opening msstyleeditor, and the "Test Theme" function does not work. It's the same error when opening msstyleeditor with the classic theme (but in this case it's normal, because the classic theme is the absence of a visual style.

![msstyleEditor_9SfS618xx4](https://user-images.githubusercontent.com/100134023/180422675-577615d7-62ba-46b9-9cbc-b5ed5eace4b6.png)

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this

EDIT : I managed to find a solution by modifying the XML manifest of the program with RessourceHacker by following this method: https://docs.microsoft.com/en-us/windows/win32/controls/supporting-high-contrast-themes

Now the controls in the control preview window do use the high contrast theme (and no longer the classic theme), and the well-recognized high contrast aerolite theme as a visual style, which makes the test theme function work. On the other hand, I get display problems when applying a modified version of aerolite.mssstyle in high contrast mode, but this is yet another problem, unrelated to the previous one.

Before :
![msstyleEditor_EHJPBV7StV](https://user-images.githubusercontent.com/100134023/180432099-f511f7d8-8710-4eb7-80f3-7f4e84150d72.png)

After : 
![msstyleEditor_NGeJQqwIBH](https://user-images.githubusercontent.com/100134023/180432409-93107c32-52c7-4664-84aa-8595bd70cef4.png)

There is still a display issue with the highlighted button text being black instead of white, an issue with the gray button not having the correct color, but otherwise it seems to work fine 👍.

Example of Explorer window with high contrast (the "OK" highlighted button and the grayed "Appliquer" button does not appear the same :
![explorer_nQWxrmmR4q](https://user-images.githubusercontent.com/100134023/180432794-1a3ed40d-3afe-40be-be8b-efa4198a7f82.png)

**Comment by OrthodoxWindows** [comment]
I would like to make a pull request but I can't find the XML manifest file.

**Comment by nptr** [comment]
Good catch! I'll have a look at it. Sorry for the late response.

**Comment by OrthodoxWindows** [comment]
Thank you !
