### ISSUE TITLE
Can't change anything, theme is not applied.

### ISSUE THREAD

**Issue by VerMishelb** [nptr/msstyleEditor#91]
*Windows Version*: Win 10 21H2 19044.1826

**Question**
Applying theme brings up "Please wait..." screen but in the end the default aero.msstyle is being used. Testing theme doesn't work at all. I'm pretty sure I'm doing something wrong but I have no idea what exactly.

**Things you already tried**
Copied default aero.msstyle to other place, exported Button/PUSHBUTTON, made some changes in photoshop, resaved, imported back replacing the original one (it's displayed in editor just fine). Saved the theme as "aeromish.msstyle" for the sake of testing stuff. Pressing Test button brings up 0x80070490 HRESULT exception (Element not found). Putting the theme to Themes folder and making a copy of aero.theme with replaced VisualStyles path with further application via SecureUxTheme ThemeTool brings up "please wait..." then uses aero.msstyle anyway. ThemeTool log doesn't say anything about going wrong.

**Checklist**
- [X] My uxtheme.dll is patched (well, ThemeTool installation was made, without applying hooks to explorer, SystemSettings and LogonUI though, so I'm not sure if it counts as "patched").
- [X] I am using the latest version of msstyleEditor.
- [X] I checked the Wiki.
- [X] None of the other issues cover this (couldn't personally find).

**Comment by nptr** [comment]
It looks like theme activation fails altogether. I'd suspect that the theme is corrupted or its dependencies are missing - this was a long standing issue that I only fixed recently (and thought to have fully fixed). Some background info, depending on how much you care: https://github.com/nptr/msstyleEditor/issues/67

To know more, I'd need to have your original Aero style (the complete folder) as well as the modified one (either .msstyles or the whole modified folder). I can then test locally and inspect the exported style for any faults.

For now I can only guess. I'd hope that it's just some language resource (MUI) thing that I didn't get right and now Windows complains because it can't find the image for the pushbutton. That would be the easiest to fix.

**Comment by VerMishelb** [comment]
I've uploaded entire Themes folder (https://drive.google.com/file/d/128TThckCdaiVA0AGBCNcKdVrrpEvJtjW/view?usp=sharing). This includes modified aeromish.msstyle (and aerolite.theme left from when I discovered the high contrast theme). The rest should be as it was in original, I didn't modify anything else.

**Comment by nptr** [comment]
I think i see the problem. It has to do with multilingual resources and the that they are located by naming convention.

Opening "[folder]/aero.msstyles" makes Windows API search for "[folder]/[language]/aero.msstyles.mui". 
msstyleEditor then has all data available. It will **merge the language resources into the .msstyles** file when saving so the language folders are no longer needed.

If you rename the **original file** before opening it for the **first time**, then Windows and msstyleEditor won't find the language dependent resources and can't make it relocatable. "[folder]/[language}/[renamedstyle].msstyles.mui" is then still necessary.

**Workaround:** Open aero.msstyles when it is still next to the language folders and save it somewhere else. It should now be relocatable and you won't have to worry about it again. You'll have to redo your changes then.

I'll change msstyleEditor to emit a warning if something like that happens. I'll also change the documentation to not be misleading with the whole renaming thing.

Let me know if that indeed fixed the issue.

**Comment by VerMishelb** [comment]
I've opened aero.msstyles and finally noticed that there are in fact two save buttons, with and without MUI.

Saving without MUI doesn't cause problems. However, now the test button throws HRESULT E_FAIL after execution of some COM component (which of course is not specified because WinAPI, I guess).

Saving with MUI throws "Updating string resource with id '7' failed with error '50'".

And while I was writing, for some reason opening aero.msstyle and editing it doesn't cause any errors now and the theme is applied when I press test...?

Oh for GOD'S sake I understood. PNG 8. It doesn't support it. If I use a regular PNG it works. If I use PNG 8 I get HRESULT E_FAIL. Fun stuff. ~~Also there is one misplaced pixel in pushbutton hover state I can't unsee.~~

I'll do something with theme and if it won't work I'll write another reply here.

**Comment by VerMishelb** [comment]
I've finished whatever I was trying to do and the results are somehow strange. When I press "test" it works all fine, except for window corner and stuff I haven't figured out yet. However, when I use ThemeTool to apply it, buttons glyphs corrupt and the title bar receives a colour.
Test:
![Test](https://user-images.githubusercontent.com/57833258/183225584-d0e50465-c98d-415e-bb88-3fa4bc59657d.png)
ThemeTool applying the same theme:
![ThemeTool](https://user-images.githubusercontent.com/57833258/183225588-be40e626-6f69-4908-bbfe-15be2a07783b.png)

**Comment by nptr** [comment]
The PNG 8 issue I can work around in code. Or at least warn about.

With the window frame and button gylphs I don't know yet. ThemeTool applies the themes from the Windows theme folder. Namaszo uses COM for that.

I am saving the style temporary in User/Public/Documents and then use Win32 API (wrapping COM) to apply it. It's not as "direct" but has some other advantages.

That's were the differences might come from. More dependency issues maybe even.
