### ISSUE TITLE
Find & Replace

### ISSUE THREAD

**Issue by BlafKing** [nptr/msstyleEditor#95]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd really love to see a "find & replace" feature in addition to the current find feature.
For me personally it would be really helpful to change a bunch of the same colors at once!

**Describe alternatives you've considered**
Doing it by hand :,)

**Comment by nptr** [comment]
Hmm, i think thats a reasonable feature. I'll give it a weak yes. No timeline tho.

**Comment by boromyr** [comment]
+1

**Comment by MindMayhem** [comment]
+1

**Comment by MindMayhem** [comment]
@nptr any news on this feature?

**Comment by nptr** [comment]
Sorry, nothing new. I am not really working on msstyleEditor at the moment.

**Comment by IndustrialOne** [comment]
Desperately needs to be added. Great program but so tedious.

**Comment by nptr** [comment]
New release coming soon!

**Comment by nptr** [comment]
Here a pre-release build, until I actually get to making a proper release.
This version adds a "replace next item" button in the search dialog.
[msstyleEditor_issue95.zip](https://github.com/user-attachments/files/15859720/msstyleEditor_issue95.zip)

Feedback is appreciated :)

**Comment by nptr** [comment]
[Version 2.1.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.0.0) includes the requested feature, so i am closing this issue now. Feel free to reopen it in case something doesn't quite work.

**Comment by e-t-l** [comment]
It does work! But would it be too much to add to include (maybe as a checkbox?) an option for "Replace ALL"?

I'm using this feature now for the same reason as OP, to replace some color property values (specifically, text colors). I want the replacement to be consistent throughout the style, which means I'm rapid-clicking the Replace button a thousand times to iterate through every match. It would be VERY nice to be able to click one button and replace a bunch of values at once.

**Comment by feeas** [comment]
@nptr  Replacing one by one is too slow. I would like to request a 'Replace All' feature.
